### ISSUE TITLE
Initial screen load on OSX shows visual artifacting on all examples

### ISSUE THREAD

**Issue by deckarep** [hajimehoshi/ebiten#749] opened 2018-12-16 20:11 UTC
First thanks for this amazingly powerful game library. I’ve been really impressed by how thorough it is and performant!

One question: on OSX all examples initially show a screen full of visual artifacts while the graphics subsystem is being initialized.

This issue appears for less than a second.

Is this something that is known or others have reported?  Or is there a way to hide this experience before the game starts?

This seems to be the case for all examples provided.

**Comment by hajimehoshi** [comment] 2018-12-17 00:55
Hi, thank you for reporting!

I'm always using macOS to test this lib, but I've not found such artifacts yet. This has not been reported yet.

I plan to upload the Metal version instead of OpenGL version soon, so the situation can be changed. I'll notify you when I do.

**Comment by hajimehoshi** [comment] 2018-12-19 17:38
Now #621 is finished, I was wondering if this problem still happens.

**Comment by hajimehoshi** [comment] 2018-12-27 15:31
Let me close this. Feel free to reopen this if you find a similar problem again. Thanks!

**Closed by hajimehoshi** 2018-12-27 15:31 UTC
Labels: bug, os:macos

**Comment by deckarep** [comment] 2018-12-28 21:10
So, I need to try this on a newer Mac...my current Mac doesn't support Metal so it just errors out.

**Comment by hajimehoshi** [comment] 2018-12-28 21:41
I thought even MacBook Pro 2013 supported Metal. Perhaps yours is older than that?

**Comment by hajimehoshi** [comment] 2018-12-28 21:56
If there are more Mac machines that don't support Metal than I expect, I'd need to implement OpenGL fallback. The problem is that there is not way to test this with my actual machines...
