### ISSUE TITLE
Rendering 1x1 image with a big scale like x64 doesn't work on Windows

### ISSUE THREAD

**Issue by sanrentai** [hajimehoshi/ebiten#1381] opened 2020-10-05 08:56 UTC
var dst *ebiten.Image  // define a Image
emptyImage, _ := ebiten.NewImage(4, 4, ebiten.FilterDefault)    
emptyImage.Fill(color.White)    
op.GeoM.Scale(32.0, 32.0)   // if 31.0 it works ok if bigger then 32 it do not work  
dst.DrawImage(emptyImage, op)

**Comment by hajimehoshi** [comment] 2020-10-05 09:09
Hi, how doesn't this work? Did you see an error message?

**Comment by sanrentai** [comment] 2020-10-21 06:11
It doesn't draw the image with height and width when use (32.0, 32.0) on dst
no error message
It draw the image with height and width when use (31.0, 31.0) on dst

**Comment by hajimehoshi** [comment] 2020-10-21 06:13
Is this reproduceable with the latest version (v1.12.2)?

**Comment by elamre** [comment] 2020-12-22 23:51
I have the same issue, also using the ebitenutil drawline and drawrect are not working because of this. 
I figured out that it has to do with the size of the image. 

	img := ebiten.NewImage(1, 1)
	img.Fill(color.White)
	op := &ebiten.DrawImageOptions{}
	log.Printf("{%f, %f} [%f %f]",c.positionX,c.positionY,c.pixelWidth,c.pixelHeight)
	op.GeoM.Scale(31,31)
	op.GeoM.Translate(c.positionX+1, c.positionY+1)
	op.ColorM.Scale(1,1,1,1)
	screen.DrawImage(img, op)

Here you can maximum scale it to 31, scaling it to 32 (either x or y) will result in the image not showing at all.

If the NewImage parameters are changed to a larger value, the scaling also can reach a higher number.
I'm using the latest version. Maybe its some limitation, but i didn't see anything in the API, or in the ebitenutil mentioning this

**Comment by elamre** [comment] 2020-12-22 23:52
So a quick workaround would be to just increase the size of the image if you are still running against this issue @sanrentai

**Comment by hajimehoshi** [comment] 2020-12-23 03:01
Confirmed this worked as expected with the latest version 2.0.2.

```go
package main

import (
        "image/color"

        "github.com/hajimehoshi/ebiten/v2"
        "github.com/hajimehoshi/ebiten/v2/ebitenutil"
)

var img = ebiten.NewImage(1, 1)

func init() {
        img.Fill(color.White)
}

type Game struct{}

func (*Game) Update() error {
        return nil
}

func (*Game) Draw(screen *ebiten.Image) {
        ebitenutil.DrawRect(screen, 0, 0, 32, 32, color.White)


        op := &ebiten.DrawImageOptions{}
        op.GeoM.Scale(32, 32)
        op.GeoM.Translate(100, 100)
        screen.DrawImage(img, op)
}

func (*Game) Layout(int, int) (int, int) {
        return 320, 240
}

func main() {
        ebiten.RunGame(&Game{})
}
```

**Comment by hajimehoshi** [comment] 2020-12-23 03:05
@elamre  Which environment are you using? Thanks.

* OS (the result of `neofetch` would be best if possible)
* Ebiten version

**Comment by elamre** [comment] 2020-12-23 07:26
That also works for me. But setting the scale to 64 64 makes the rectangle disappear. I'm using ebiten v2.0.2.
Running on windows 10 enterprice, build 19042.685

I changed the shapes.go:26 to:

	emptyImage = ebiten.NewImage(32, 32)

Now it works. But by default it does not

**Comment by hajimehoshi** [comment] 2020-12-23 08:26
Thanks. I changed the scale to 64 but could not reproduce the issue on Windows (Parallels on macOS). I'll try another machine, but this might be an issue that happens in a specific GPU.

**Comment by elamre** [comment] 2020-12-23 08:31
I'm running it on my laptop, which has no discrete graphics. which is i5-8350U, so running on the Intel® UHD Graphics 620. I have unfortunately no way to try it on other platforms or OS

**Comment by hajimehoshi** [comment] 2020-12-23 08:44
With 64:

![image](https://user-images.githubusercontent.com/16950/102977165-f6c38200-4545-11eb-8e9f-112b9048ba05.png)

(Intel Iris Pro Graphics 5200)

@elamre So in your environment, nothing is rendered, right? Thank you for the graphics information!

**Comment by elamre** [comment] 2020-12-23 08:49
Nothing is rendered.
![image](https://user-images.githubusercontent.com/1455419/102977904-f1ddde80-4503-11eb-8d20-129a4a06a87d.png)
This is with 64 for me. Where I changed the shapes file. You can see that the drawrect function works (since it has a larger "empty" image) but the screen.DrawImage (with 1x1 pixel empty image) is not working.

**Comment by hajimehoshi** [comment] 2020-12-23 08:54
That's an interesting issue.

In general, if you want to render a rectangle with ebiten.Image, it is recommended to use a SubImage of a little bigger image, as DrawRect already does. Otherwise, edges can be missing. However, I have not expected that nothing was rendered when the image is 1x1. This sounds a bug, but unfortunately this cannot be reproduced on my environment.

As using a too-small image is not recommended, I'll make this a low-priority issue, even though this might be a bug. At least I would have to write documents. Further information is welcome.

**Comment by hajimehoshi** [comment] 2020-12-23 09:07
@elamre Would it be possible to update the graphics driver? There was another bug with Intel UHD Graphics 620 https://github.com/hajimehoshi/ebiten/issues/1419, and updating the driver fixed that.

**Comment by elamre** [comment] 2020-12-23 09:26
Very interesting... I updated my driver to the latest version supplied by the notebook manufacturer, 27.20.100.8189, and now everything seems to work as expected.

**Comment by hajimehoshi** [comment] 2020-12-23 09:31
Thank you for confirming! And I believe that @sanrentai also uses the same GPU, and sanrentai is the same reporter of #1419.

I'll close this as 'won't fix'.

**Closed by hajimehoshi** 2020-12-23 09:31 UTC
Labels: bug, help-wanted, os:windows, question
