### ISSUE TITLE
internal/graphicsdriver/directx: `SubImage` as a destination should work more efficiently with DirectX

### ISSUE THREAD

**Issue by erexo** [hajimehoshi/ebiten#2232] opened 2022-08-04 08:13 UTC
Calling `ebiten.Image's` `SubImage` function excessive number of times during game loop may cause a significant performance drop while rendering on DirectX.
Using below example on my Windows machine I can reach about 500 FPS while not using SubImage function, and when I do the FPS drops to 90.
Interesting thing is that the FPS does not drop linearly to the number of SubImages created in a loop. In given example on my machine creating 28 SubImages has marginal impact on performance, but 29 SubImages causes a massive FPS drop.

```go
package main
 
import (
    "fmt"
    "image"
    "image/color"
 
    "github.com/hajimehoshi/ebiten/v2"
    "github.com/hajimehoshi/ebiten/v2/ebitenutil"
)
 
const useSubImage = true
const size = 100
 
func main() {
    ebiten.SetWindowSize(800, 600)
    ebiten.SetVsyncEnabled(false)
 
    img := ebiten.NewImage(size, size)
    img.Fill(color.Black)
    ebiten.RunGame(&game{
        img: img,
    })
}
 
type game struct {
    img *ebiten.Image
}
 
func (g *game) Update() error { return nil }
 
func (g *game) Draw(screen *ebiten.Image) {
    for x := 0; x < 8; x++ {
        for y := 0; y < 6; y++ {
            r := image.Rect(x*size, y*size, x*size+size, y*size+size)
            sub := screen
            if useSubImage {
                sub = screen.SubImage(r).(*ebiten.Image)
            }
            op := ebiten.DrawImageOptions{
                CompositeMode: ebiten.CompositeModeSourceOver,
            }
            op.GeoM.Translate(float64(x*size), float64(y*size))
            sub.DrawImage(g.img, &op)
        }
    }
 
    ebitenutil.DebugPrint(screen, fmt.Sprintf("FPS: %.0f", ebiten.CurrentFPS()))
}
 
func (g *game) Layout(outsideWidth, outsideHeight int) (int, int) {
    return outsideWidth, outsideHeight
}
```

**Comment by hajimehoshi** [comment] 2022-08-04 13:44
Confirmed that `useSubImage` changed the performance drastically.

**Comment by hajimehoshi** [comment] 2022-08-04 13:58
This is simply because the commands are not merged:

With `useSubImage = true`

```
Internal image sizes:
  1: (1024, 1024)
  2: (16, 16)
  3: (16, 16)
  4: (16, 16)
  6: (1024, 1024)
  7: (1600, 1200)
Graphics commands:
  draw-triangles: dst: 6 <- src: [1, (nil), (nil), (nil)], default shader, dst region: (x:0, y:0, width:800, height:600), num of indices: 6, colorm: Identity[], mode: copy, filter: nearest, address: unsafe, even-odd: false
  draw-triangles: dst: 6 <- src: [1, (nil), (nil), (nil)], default shader, dst region: (x:0, y:0, width:100, height:100), num of indices: 6, colorm: Identity[], mode: source-over, filter: nearest, address: unsafe, even-odd: false
  draw-triangles: dst: 6 <- src: [1, (nil), (nil), (nil)], default shader, dst region: (x:0, y:100, width:100, height:100), num of indices: 6, colorm: Identity[], mode: source-over, filter: nearest, address: unsafe, even-odd: false
  draw-triangles: dst: 6 <- src: [1, (nil), (nil), (nil)], default shader, dst region: (x:0, y:200, width:100, height:100), num of indices: 6, colorm: Identity[], mode: source-over, filter: nearest, address: unsafe, even-odd: false
  draw-triangles: dst: 6 <- src: [1, (nil), (nil), (nil)], default shader, dst region: (x:0, y:300, width:100, height:100), num of indices: 6, colorm: Identity[], mode: source-over, filter: nearest, address: unsafe, even-odd: false
  draw-triangles: dst: 6 <- src: [1, (nil), (nil), (nil)], default shader, dst region: (x:0, y:400, width:100, height:100), num of indices: 6, colorm: Identity[], mode: source-over, filter: nearest, address: unsafe, even-odd: false
  draw-triangles: dst: 6 <- src: [1, (nil), (nil), (nil)], default shader, dst region: (x:0, y:500, width:100, height:100), num of indices: 6, colorm: Identity[], mode: source-over, filter: nearest, address: unsafe, even-odd: false
  draw-triangles: dst: 6 <- src: [1, (nil), (nil), (nil)], default shader, dst region: (x:100, y:0, width:100, height:100), num of indices: 6, colorm: Identity[], mode: source-over, filter: nearest, address: unsafe, even-odd: false
  draw-triangles: dst: 6 <- src: [1, (nil), (nil), (nil)], default shader, dst region: (x:100, y:100, width:100, height:100), num of indices: 6, colorm: Identity[], mode: source-over, filter: nearest, address: unsafe, even-odd: false
  draw-triangles: dst: 6 <- src: [1, (nil), (nil), (nil)], default shader, dst region: (x:100, y:200, width:100, height:100), num of indices: 6, colorm: Identity[], mode: source-over, filter: nearest, address: unsafe, even-odd: false
  draw-triangles: dst: 6 <- src: [1, (nil), (nil), (nil)], default shader, dst region: (x:100, y:300, width:100, height:100), num of indices: 6, colorm: Identity[], mode: source-over, filter: nearest, address: unsafe, even-odd: false
  draw-triangles: dst: 6 <- src: [1, (nil), (nil), (nil)], default shader, dst region: (x:100, y:400, width:100, height:100), num of indices: 6, colorm: Identity[], mode: source-over, filter: nearest, address: unsafe, even-odd: false
  draw-triangles: dst: 6 <- src: [1, (nil), (nil), (nil)], default shader, dst region: (x:100, y:500, width:100, height:100), num of indices: 6, colorm: Identity[], mode: source-over, filter: nearest, address: unsafe, even-odd: false
  draw-triangles: dst: 6 <- src: [1, (nil), (nil), (nil)], default shader, dst region: (x:200, y:0, width:100, height:100), num of indices: 6, colorm: Identity[], mode: source-over, filter: nearest, address: unsafe, even-odd: false
  draw-triangles: dst: 6 <- src: [1, (nil), (nil), (nil)], default shader, dst region: (x:200, y:100, width:100, height:100), num of indices: 6, colorm: Identity[], mode: source-over, filter: nearest, address: unsafe, even-odd: false
  draw-triangles: dst: 6 <- src: [1, (nil), (nil), (nil)], default shader, dst region: (x:200, y:200, width:100, height:100), num of indices: 6, colorm: Identity[], mode: source-over, filter: nearest, address: unsafe, even-odd: false
  draw-triangles: dst: 6 <- src: [1, (nil), (nil), (nil)], default shader, dst region: (x:200, y:300, width:100, height:100), num of indices: 6, colorm: Identity[], mode: source-over, filter: nearest, address: unsafe, even-odd: false
  draw-triangles: dst: 6 <- src: [1, (nil), (nil), (nil)], default shader, dst region: (x:200, y:400, width:100, height:100), num of indices: 6, colorm: Identity[], mode: source-over, filter: nearest, address: unsafe, even-odd: false
  draw-triangles: dst: 6 <- src: [1, (nil), (nil), (nil)], default shader, dst region: (x:200, y:500, width:100, height:100), num of indices: 6, colorm: Identity[], mode: source-over, filter: nearest, address: unsafe, even-odd: false
  draw-triangles: dst: 6 <- src: [1, (nil), (nil), (nil)], default shader, dst region: (x:300, y:0, width:100, height:100), num of indices: 6, colorm: Identity[], mode: source-over, filter: nearest, address: unsafe, even-odd: false
  draw-triangles: dst: 6 <- src: [1, (nil), (nil), (nil)], default shader, dst region: (x:300, y:100, width:100, height:100), num of indices: 6, colorm: Identity[], mode: source-over, filter: nearest, address: unsafe, even-odd: false
  draw-triangles: dst: 6 <- src: [1, (nil), (nil), (nil)], default shader, dst region: (x:300, y:200, width:100, height:100), num of indices: 6, colorm: Identity[], mode: source-over, filter: nearest, address: unsafe, even-odd: false
  draw-triangles: dst: 6 <- src: [1, (nil), (nil), (nil)], default shader, dst region: (x:300, y:300, width:100, height:100), num of indices: 6, colorm: Identity[], mode: source-over, filter: nearest, address: unsafe, even-odd: false
  draw-triangles: dst: 6 <- src: [1, (nil), (nil), (nil)], default shader, dst region: (x:300, y:400, width:100, height:100), num of indices: 6, colorm: Identity[], mode: source-over, filter: nearest, address: unsafe, even-odd: false
  draw-triangles: dst: 6 <- src: [1, (nil), (nil), (nil)], default shader, dst region: (x:300, y:500, width:100, height:100), num of indices: 6, colorm: Identity[], mode: source-over, filter: nearest, address: unsafe, even-odd: false
  draw-triangles: dst: 6 <- src: [1, (nil), (nil), (nil)], default shader, dst region: (x:400, y:0, width:100, height:100), num of indices: 6, colorm: Identity[], mode: source-over, filter: nearest, address: unsafe, even-odd: false
  draw-triangles: dst: 6 <- src: [1, (nil), (nil), (nil)], default shader, dst region: (x:400, y:100, width:100, height:100), num of indices: 6, colorm: Identity[], mode: source-over, filter: nearest, address: unsafe, even-odd: false
  draw-triangles: dst: 6 <- src: [1, (nil), (nil), (nil)], default shader, dst region: (x:400, y:200, width:100, height:100), num of indices: 6, colorm: Identity[], mode: source-over, filter: nearest, address: unsafe, even-odd: false
  draw-triangles: dst: 6 <- src: [1, (nil), (nil), (nil)], default shader, dst region: (x:400, y:300, width:100, height:100), num of indices: 6, colorm: Identity[], mode: source-over, filter: nearest, address: unsafe, even-odd: false
  draw-triangles: dst: 6 <- src: [1, (nil), (nil), (nil)], default shader, dst region: (x:400, y:400, width:100, height:100), num of indices: 6, colorm: Identity[], mode: source-over, filter: nearest, address: unsafe, even-odd: false
  draw-triangles: dst: 6 <- src: [1, (nil), (nil), (nil)], default shader, dst region: (x:400, y:500, width:100, height:100), num of indices: 6, colorm: Identity[], mode: source-over, filter: nearest, address: unsafe, even-odd: false
  draw-triangles: dst: 6 <- src: [1, (nil), (nil), (nil)], default shader, dst region: (x:500, y:0, width:100, height:100), num of indices: 6, colorm: Identity[], mode: source-over, filter: nearest, address: unsafe, even-odd: false
  draw-triangles: dst: 6 <- src: [1, (nil), (nil), (nil)], default shader, dst region: (x:500, y:100, width:100, height:100), num of indices: 6, colorm: Identity[], mode: source-over, filter: nearest, address: unsafe, even-odd: false
  draw-triangles: dst: 6 <- src: [1, (nil), (nil), (nil)], default shader, dst region: (x:500, y:200, width:100, height:100), num of indices: 6, colorm: Identity[], mode: source-over, filter: nearest, address: unsafe, even-odd: false
  draw-triangles: dst: 6 <- src: [1, (nil), (nil), (nil)], default shader, dst region: (x:500, y:300, width:100, height:100), num of indices: 6, colorm: Identity[], mode: source-over, filter: nearest, address: unsafe, even-odd: false
  draw-triangles: dst: 6 <- src: [1, (nil), (nil), (nil)], default shader, dst region: (x:500, y:400, width:100, height:100), num of indices: 6, colorm: Identity[], mode: source-over, filter: nearest, address: unsafe, even-odd: false
  draw-triangles: dst: 6 <- src: [1, (nil), (nil), (nil)], default shader, dst region: (x:500, y:500, width:100, height:100), num of indices: 6, colorm: Identity[], mode: source-over, filter: nearest, address: unsafe, even-odd: false
  draw-triangles: dst: 6 <- src: [1, (nil), (nil), (nil)], default shader, dst region: (x:600, y:0, width:100, height:100), num of indices: 6, colorm: Identity[], mode: source-over, filter: nearest, address: unsafe, even-odd: false
  draw-triangles: dst: 6 <- src: [1, (nil), (nil), (nil)], default shader, dst region: (x:600, y:100, width:100, height:100), num of indices: 6, colorm: Identity[], mode: source-over, filter: nearest, address: unsafe, even-odd: false
  draw-triangles: dst: 6 <- src: [1, (nil), (nil), (nil)], default shader, dst region: (x:600, y:200, width:100, height:100), num of indices: 6, colorm: Identity[], mode: source-over, filter: nearest, address: unsafe, even-odd: false
  draw-triangles: dst: 6 <- src: [1, (nil), (nil), (nil)], default shader, dst region: (x:600, y:300, width:100, height:100), num of indices: 6, colorm: Identity[], mode: source-over, filter: nearest, address: unsafe, even-odd: false
  draw-triangles: dst: 6 <- src: [1, (nil), (nil), (nil)], default shader, dst region: (x:600, y:400, width:100, height:100), num of indices: 6, colorm: Identity[], mode: source-over, filter: nearest, address: unsafe, even-odd: false
  draw-triangles: dst: 6 <- src: [1, (nil), (nil), (nil)], default shader, dst region: (x:600, y:500, width:100, height:100), num of indices: 6, colorm: Identity[], mode: source-over, filter: nearest, address: unsafe, even-odd: false
  draw-triangles: dst: 6 <- src: [1, (nil), (nil), (nil)], default shader, dst region: (x:700, y:0, width:100, height:100), num of indices: 6, colorm: Identity[], mode: source-over, filter: nearest, address: unsafe, even-odd: false
  draw-triangles: dst: 6 <- src: [1, (nil), (nil), (nil)], default shader, dst region: (x:700, y:100, width:100, height:100), num of indices: 6, colorm: Identity[], mode: source-over, filter: nearest, address: unsafe, even-odd: false
  draw-triangles: dst: 6 <- src: [1, (nil), (nil), (nil)], default shader, dst region: (x:700, y:200, width:100, height:100), num of indices: 6, colorm: Identity[], mode: source-over, filter: nearest, address: unsafe, even-odd: false
  draw-triangles: dst: 6 <- src: [1, (nil), (nil), (nil)], default shader, dst region: (x:700, y:300, width:100, height:100), num of indices: 6, colorm: Identity[], mode: source-over, filter: nearest, address: unsafe, even-odd: false
  draw-triangles: dst: 6 <- src: [1, (nil), (nil), (nil)], default shader, dst region: (x:700, y:400, width:100, height:100), num of indices: 6, colorm: Identity[], mode: source-over, filter: nearest, address: unsafe, even-odd: false
  draw-triangles: dst: 6 <- src: [1, (nil), (nil), (nil)], default shader, dst region: (x:700, y:500, width:100, height:100), num of indices: 6, colorm: Identity[], mode: source-over, filter: nearest, address: unsafe, even-odd: false
  draw-triangles: dst: 6 <- src: [1, (nil), (nil), (nil)], default shader, dst region: (x:0, y:0, width:800, height:600), num of indices: 42, colorm: Identity[], mode: source-over, filter: nearest, address: unsafe, even-odd: false
  draw-triangles: dst: 7 (screen) <- src: [6, (nil), (nil), (nil)], default shader, dst region: (x:0, y:0, width:1600, height:1200), num of indices: 6, colorm: Identity[], mode: copy, filter: nearest, address: unsafe, even-odd: false
```

Without `useSubImage = false`

```
Update count per frame: 1
Internal image sizes:
  1: (1024, 1024)
  2: (16, 16)
  3: (16, 16)
  4: (16, 16)
  6: (1024, 1024)
  7: (1600, 1200)
Graphics commands:
  draw-triangles: dst: 6 <- src: [1, (nil), (nil), (nil)], default shader, dst region: (x:0, y:0, width:800, height:600), num of indices: 6, colorm: Identity[], mode: copy, filter: nearest, address: unsafe, even-odd: false
  draw-triangles: dst: 6 <- src: [1, (nil), (nil), (nil)], default shader, dst region: (x:0, y:0, width:800, height:600), num of indices: 330, colorm: Identity[], mode: source-over, filter: nearest, address: unsafe, even-odd: false
  draw-triangles: dst: 7 (screen) <- src: [6, (nil), (nil), (nil)], default shader, dst region: (x:0, y:0, width:1600, height:1200), num of indices: 6, colorm: Identity[], mode: copy, filter: nearest, address: unsafe, even-odd: false
```

The commands should be merged anyway.

**Comment by hajimehoshi** [comment] 2022-08-04 14:06
Using a sub image for destinations should be rare. I remove the milestone from this issue.

**Comment by hajimehoshi** [comment] 2022-10-02 16:57
Unfortunately I cannot come up with a good solution in such usages. Please avoid successive usages of various regions of an image.

**Comment by hajimehoshi** [comment] 2022-10-08 15:57
Reported that the performance was not bad with OpenGL, but bad with DirectX

**Comment by erexo** [comment] 2022-10-27 09:02
A of Ebiten v2.4.8, OpenGL performance is still better on Windows than DirectX by around 20%.
This may not be caused only by drawing on subimage, when I lowered number of subimage draws the percentage difference remains more or less the same.
@hajimehoshi you do have access to my sources, if you wish I can guide you on how to run the game so you could debug it yourself

**Comment by erexo** [comment] 2022-10-28 11:44
![image](https://user-images.githubusercontent.com/6548968/198579500-3f002e5c-c7ee-44d4-8f47-1f424cf13bfd.png)

and as I predicted, players did start to notice this. That's why I've added an option to change the graphics engine

**Comment by hajimehoshi** [comment] 2022-10-28 11:59
Yeah so it took time to realize that this was a DirectX issue. From the first report, I couldn't understand that

**Comment by hajimehoshi** [comment] 2022-10-29 10:08
Note to myself: omit passing `dstRegion` as uniform variables, when the shader doesn't use them.

**Comment by hajimehoshi** [comment] 2022-11-04 11:50
@erexo Could you try d73e8f785d27f68536cdae8983418a5d6a8cf7f7? Thanks,

**Closed** 2022-11-04 11:49 UTC
Labels: os:windows, performance

**Comment by erexo** [comment] 2022-11-05 15:16
> @erexo Could you try [d73e8f7](https://github.com/hajimehoshi/ebiten/commit/d73e8f785d27f68536cdae8983418a5d6a8cf7f7)? Thanks,

I've tested my game against v2.4.7 and current head, and those are the results:
old (v2.4.7):
opengl: 750-830fps
direct: 320-370fps
new (~HEAD, e9754c7bc6747ff33bec890e4315afb65bd8b01a):
opengl: 580-630fps
direct: 260-320fps

**Comment by hajimehoshi** [comment] 2022-11-05 15:24
Have you tested the original code (using various destination regions)?

**Comment by erexo** [comment] 2022-11-05 17:27
Original code tests:
```
- v2.4.11
directX: true = 100 fps, false = 900 fps
opengl: true = 1800 fps, false = 2200 fps
- e9754c7bc6747ff33bec890e4315afb65bd8b01a
directX: true, = 800 fps, false = 800 fps
opengl: true = 1750 fps, false = 2000 fps
```

The issue seems to be resolved, thank you for your work :)
