### ISSUE TITLE
ebitenutil: DebugPrint is slow (DrawTriangles vs DrawImage performance?)

### ISSUE THREAD

**Issue by Zyko0** [hajimehoshi/ebiten#1880] opened 2021-11-16 19:28 UTC
There seem to be a real difference between mapping multiple vertices and calling `DrawTriangles` once compared to creating SubImages and calling `DrawImage` multiple times.

The observation came from `ebitenutil.DebugPrint` being quite slow, and when used to display `ebiten.CurrentFPS()`, it might not be 100% representative since the call itself costs quite a lot (with `FPSModeVsyncOffMaximum` in order to be able to measure rendering performances).

Adding a test method `DebugPrintWithTrianglesAt` to [ebitenutil/debugprint.go](https://github.com/hajimehoshi/ebiten/blob/v2.3.0-alpha.2/ebitenutil/debugprint.go) by changing its content to https://gist.github.com/Zyko0/785d079c9b9facbacc3df56c279d8f73 allowed me to do a 60 second profiling test using `pprof` with the following [main.go](https://gist.github.com/Zyko0/72157a88c409f4a580f7e896934fa70a)

Results using `go tool pprof profile.prof` gives me the following outputs (60sec run):
* `(pprof) list Draw`
```
         .          .     77:   // Text drawing
         .      4.85s     78:   ebitenutil.DebugPrint(screen, str)
      10ms      2.68s     79:   ebitenutil.DebugPrintWithTrianglesAt(screen, str, 0, 20)
         .      3.17s     80:   text.Draw(screen, str, face, 0, 50, color.RGBA{255, 255, 255, 255})
```
* `(pprof) list drawDebugText`
```
ROUTINE ======================== github.com/hajimehoshi/ebiten/v2/ebitenutil.drawDebugText in github.com\hajimehoshi\ebiten\v2@v2.3.0-alpha.2\ebitenutil\debugprint.go    
     150ms      4.85s (flat, cum) 12.03% of Total
         .          .     47:           op.ColorM.Scale(0, 0, 0, 0.5)
         .          .     48:   }
         .          .     49:   x := 0
         .          .     50:   y := 0
         .          .     51:   w, _ := debugPrintTextImage.Size()
      40ms       40ms     52:   for _, c := range str {
         .          .     53:           const (
         .          .     54:                   cw = assets.CharWidth
         .          .     55:                   ch = assets.CharHeight
         .          .     56:           )
         .          .     57:           if c == '\n' {
         .          .     58:                   x = 0
         .          .     59:                   y += ch
         .          .     60:                   continue
         .          .     61:           }
      40ms      400ms     62:           s, ok := debugPrintTextSubImages[c]
         .          .     63:           if !ok {
         .          .     64:                   n := w / cw
         .          .     65:                   sx := (int(c) % n) * cw
         .          .     66:                   sy := (int(c) / n) * ch
         .          .     67:                   s = debugPrintTextImage.SubImage(image.Rect(sx, sy, sx+cw, sy+ch)).(*ebiten.Image)
         .          .     68:                   debugPrintTextSubImages[c] = s
         .          .     69:           }
         .       10ms     70:           op.GeoM.Reset()
      20ms       60ms     71:           op.GeoM.Translate(float64(x), float64(y))
      10ms       10ms     72:           op.GeoM.Translate(float64(ox+1), float64(oy))
         .      4.29s     73:           rt.DrawImage(s, op)
      40ms       40ms     74:           x += cw
         .          .     75:   }
         .          .     76:}
```

Or more visually:
![image](https://user-images.githubusercontent.com/13394516/142052136-1d71fd00-5c7f-4902-ad8e-ece74a00ddd5.png)

(sorry for the verbosity)

**Comment by eliasdaler** [comment] 2021-12-24 00:45
Not surprising, since you do less draw calls.
@hajimehoshi - will you fix this soon, or should I make a PR? Seems like an easy improvement to make. :)

We can make it even better, though, if we don't reallocate vertices/indices on each call. To keep the same interface, we can just cache indices/vertices on a module level and only re-allocate if text or other parameters change.
Another alternative is to change API to be like this:

```go
str := ebiten.MakeDebugPrintString("some string") // only call it once/or when the string changes
// ... 
ebiten.DebugPrintNew(str, ...)
```

**Comment by hajimehoshi** [comment] 2021-12-24 02:09
> Not surprising, since you do less draw calls.

I don't think so but how did you check that?

**Comment by eliasdaler** [comment] 2021-12-24 02:36
Sorry, I seem to have misunderstood what Ebiten does in its current implementation and made a wild guess (based on how it looked).
Though it gives me an idea that having a Ebiten count draw calls might be a nice feature for profiling/debugging. E.g. if we could get it as we can get TPS/FPS.

**Comment by hajimehoshi** [comment] 2021-12-24 02:37
> Though it gives me an idea that having a Ebiten count draw calls might be a nice feature for profiling/debugging.

You can know that with `ebitendebug` build tag.

**Comment by hajimehoshi** [comment] 2022-07-31 13:05
@Zyko0 Has the situation changed from your last experiment? I'm not sure what was the issue, sorry...

**Comment by Zyko0** [comment] 2022-07-31 14:05
The issue was that `ebitenutil.DebugPrint` could be more efficient
I don't think the situation changed (after trying just now), this relation still exists in terms of performances:
triangles impl > text draw > debug print

**Comment by hajimehoshi** [comment] 2022-07-31 14:59
So the problem is `DrawImage` is not performant compared to `DrawTriangles`. Rather than reimplementing `DebugPrint` with `DrawTriangles`, I want to improve `DrawImage`.

**Comment by hajimehoshi** [comment] 2022-07-31 17:05
Now `DebugPring` has been improved and the performance is good enough. Let me close this.

**Closed by hajimehoshi** 2022-07-31 17:05 UTC
Labels: performance, needs-investigation
