### ISSUE TITLE
example/windowsize: unstable FPS on macOS using Metal and VSYNC=false after moving mouse

### ISSUE THREAD

**Issue by philhassey** [hajimehoshi/ebiten#2931] opened 2024-03-16 17:19 UTC
### Ebitengine Version

v2.7.0-alpha.9

### Operating System

- [ ] Windows
- [X] macOS
- [ ] Linux
- [ ] FreeBSD
- [ ] OpenBSD
- [ ] Android
- [ ] iOS
- [ ] Nintendo Switch
- [ ] PlayStation 5
- [ ] Xbox
- [ ] Web Browsers

### Go Version (`go version`)

go version go1.22.1 darwin/arm64

### What steps will reproduce the problem?

1. `cd examples/windowresize`

2. `EBITENGINE_GRAPHICS_LIBRARY=metal go run .`
<img width="476" alt="image" src="https://github.com/hajimehoshi/ebiten/assets/723344/ddb5856a-ed1d-4991-87d9-782a39cc6d1e">

Note ~60 FPS

3. Press the "v" key to switch on vsync
<img width="450" alt="image" src="https://github.com/hajimehoshi/ebiten/assets/723344/59097b7c-a866-43fb-91ad-eb5d40998b05">

Note ~500+ FPS

4. Move the mouse, FPS drops to 60
<img width="480" alt="image" src="https://github.com/hajimehoshi/ebiten/assets/723344/6f2e1a67-5e6e-46b0-979c-3a6c5211eb6b">

### What is the expected result?

The FPS should stay high with VSYNC off even when I move the mouse.

### What happens instead?

The FPS drops to 60 when I move my mouse.

### Anything else you feel useful to add?

This doesn't happen when using OpenGL on macOS.

```
EBITENGINE_GRAPHICS_LIBRARY=opengl go run .
```

**Comment by hajimehoshi** [comment] 2024-03-16 17:20
Could you tell your mac spec? Thanks,

**Comment by philhassey** [comment] 2024-03-16 17:22
Mac specs:

<img width="483" alt="image" src="https://github.com/hajimehoshi/ebiten/assets/723344/c96702f5-67fc-418e-a0c7-008665a90b15">

<img width="476" alt="image" src="https://github.com/hajimehoshi/ebiten/assets/723344/2981b51c-0464-487d-bd68-34e3d0481f3d">

Test done on the built-in 13.3 inch display.

**Comment by hajimehoshi** [comment] 2024-03-16 17:23
Thanks. Unfortunately I don't have the same thing, but I'll try my Intel MacBook Pro later.

**Comment by hajimehoshi** [comment] 2024-03-16 17:23
Also, would it be reproducible with Ebitengine v2.6.6?

**Comment by philhassey** [comment] 2024-03-16 17:39
```
% git checkout v2.6.6
Previous HEAD position was 64cb6cf8a internal/atlas: reduce test flakiness
HEAD is now at 4f1dc6a0f .github/workflows: test Go 1.22
```

Behavior is a bit different when v2.6.6.

The FPS went up to ~200 instead of 500+ when I pressed "v".

When I moved the mouse, the FPS dropped to ~120, instead of 60.

**Comment by hajimehoshi** [comment] 2024-03-16 17:45
OK so this is a new issue. I think I know the cause but this would revert another issue...

https://github.com/hajimehoshi/ebiten/commit/055db234a11f9fc527adbe254b39fe4cda22949c

**Comment by hajimehoshi** [comment] 2024-03-16 17:50
Oh, isn't 60 an expected value as a refresh rate for a MacBook Air?

https://www.theverge.com/23149982/apple-macbook-air-vs-pro-specs-features-price-comparison

**Comment by philhassey** [comment] 2024-03-16 17:52
Seems like it's the only value?

<img width="720" alt="image" src="https://github.com/hajimehoshi/ebiten/assets/723344/33304ea7-623a-4058-a3a2-0ba2b80ec8a8">

**Comment by hajimehoshi** [comment] 2024-03-16 17:53
Yeah I think so. Rather, 120 seems a little strange (but Metal is often strange :-). So, I'll close this as WAI. Thank you for reporting!

**Closed by hajimehoshi** 2024-03-16 17:53 UTC
Labels: bug, os:macos, needs-investigation

**Comment by hajimehoshi** [comment] 2024-03-16 18:23
> The FPS should stay high with VSYNC off even when I move the mouse.

I was a little misunderstanding. I thought the main concern was that FPS didn't reach 120 (https://github.com/hajimehoshi/ebiten/issues/2822#issuecomment-2000506450), but actually the issue here is unstability of the  FPS. In any cases, I don't think this is fixable...

**Comment by philhassey** [comment] 2024-03-16 19:12
My main concern here is that when moving the mouse, it behaves as if VSYNC gets turned back on.  So I can't use Metal+VSYNC turned off to gain finer input readings.

For now I'll keep using OpenGL.  Thanks for taking a look!

**Comment by hajimehoshi** [comment] 2024-03-17 04:24
For inputting, #1704 would solve the issue in the future.
