### ISSUE TITLE
Ebitengine doesn't work on Android Termux

### ISSUE THREAD

**Issue by vsm0** [hajimehoshi/ebiten#3057] opened 2024-08-04 15:42 UTC
### Ebitengine Version

2.7.8

### Operating System

- [ ] Windows
- [ ] macOS
- [ ] Linux
- [ ] FreeBSD
- [ ] OpenBSD
- [X] Android
- [ ] iOS
- [ ] Nintendo Switch
- [ ] PlayStation 5
- [ ] Xbox
- [ ] Web Browsers

### Go Version (`go version`)

1.22.5

### What steps will reproduce the problem?

Create _main.go_ with the following contents (basic window example):

```go
package main

import (
	"github.com/hajimehoshi/ebiten/v2"
	"github.com/hajimehoshi/ebiten/v2/ebitenutil"
)

const (
	WIDTH = 480
	HEIGHT = 360
)

type Game struct {}

func (g *Game) Layout(widith, height int) (int, int) {
	return WIDTH, HEIGHT
}

func (g *Game) Update() error {
	return nil
}

func (g *Game) Draw(img *ebiten.Image) {
	ebitenutil.DebugPrint(img, "Hello World")
}

func main() {
	ebiten.SetWindowSize(WIDTH * 2, HEIGHT * 2)
	ebiten.SetWindowTitle("Untitled")

	if err := ebiten.RunGame(&Game{}); err != nil {
		panic(err)
	}
}
```

create _go.mod_ and run program:
```bash
go mod init example
go mod tidy
go run .
```

### What is the expected result?

A bare window with some text should appear.

### What happens instead?

The following error appears during compilation:
```bash
android.c:171:52: error: incompatible pointer to integer conversion passing 'ANativeWindow *' (aka 'struct ANativeWindow *') to parameter of type 'EGLNativeWindowType' (aka 'unsigned long') [-Wint-conversion]
../../../../usr/include/EGL/egl.h:136:109: note: passing argument to parameter 'win' here
```

### Anything else you feel useful to add?

The compilation environment is Termux, which is non-standard Android.

After some investigation, the clash between parameter value and signature is possibly due an incorrect/incomplete appraisal of the compilation environment, within the header __eglplatform.h__, as noted by the error.

A standard Android target (as defined in _eglplatform.h_) has the following conditional definition:

```c
#elif defined(__ANDROID__) || defined(ANDROID)
#include <android/native_window.h>
...
typedef struct ANativeWindow* EGLNativeWindowType;
```

However, Termux modifies this slightly:

```c
#elif (defined(__ANDROID__) || defined(ANDROID)) && !defined(__TERMUX__)
...                                                                 
typedef struct ANativeWindow* EGLNativeWindowType;
```

Since this definition doesn't match, I suspect it falls through to the next defined variable '__unix__' (which I confirmed by preprocessing gomobile/app/android.c using _gcc -E -dM android.c_):

```c
#elif defined(__unix__)
...
typedef khronos_uintptr_t EGLNativeWindowType;
```

It's my first time digging so deep into library internals, but unless I'm way off mark, it's possible that gomobile uses the standard eglplatform.h header, which mistakes the Termux environment for a standard Android one.

All in all, this is an issue for a specific use case, and I'm not experienced enough to know how hard or simple a fix this would be. Hopefully it isn't too niche, as it would be nice for the Termux target to be supported. It is a near complete UNIX environment that can already handle most desktop programs/tools I've thrown at it.

**Comment by hajimehoshi** [comment] 2024-08-04 15:48
I guess this is an issue in golang.org/x/mobile. If you can reproduce this with gomobile (not ebitenmobile), please report this to github.com/golang/go.

**Comment by vsm0** [comment] 2024-08-04 15:52
Thx for the reply.
I'm not sure how to do that right now, so I'll do some searching later.

**Comment by hajimehoshi** [comment] 2024-08-04 15:53
I'd try to compile an example project in golang.org/x/mobile like golang.org/x/mobile/example/basic

**Comment by vsm0** [comment] 2024-08-04 16:00
Yes the same error was produced. I'll report it there now.
Thx for the help

**Comment by hajimehoshi** [comment] 2024-08-04 16:11
Apparently gomobile doesn't work well with Termux https://github.com/golang/go/issues/47727

**Comment by vsm0** [comment] 2024-08-04 16:23
I see. I'm not sure what full native means, but besides this gomobile issue, other programs compile fine, even those with cgo. Tbh I've never even seen those errors while using Go on Termux. I've compiled other packages just fine, like raylib-go.

Since you mention the issue in the link above, should I still report my issue personally?

**Comment by hajimehoshi** [comment] 2024-08-04 16:38
> Since you mention the issue in the link above, should I still report my issue personally?

I guess so as your error (EGL) seems new. It'd be nice to add a link to 47727 as a reference.

**Comment by vsm0** [comment] 2024-08-04 16:42
Alright, will do thx

**Comment by hajimehoshi** [comment] 2024-08-04 18:11
https://github.com/golang/go/issues/68727

Didn't you test gomobile...?

**Comment by hajimehoshi** [comment] 2024-08-04 18:15
Oh, I thought you tried ebitenmobile, but what you did was just go-run. Then this is an issue in ebitengine, not in gomobile.

**Comment by vsm0** [comment] 2024-08-04 18:21
Yeah, it's not packaging for Android. It's pretty much standard Go compilation on the command line.

As a side note, I installed Go in Ubuntu from within Termux and it built successfully, but didn't run due to x11 issues.

**Comment by hajimehoshi** [comment] 2024-08-04 18:25
> Yes the same error was produced

Just in case, what did you reproduce at that time?

**Comment by vsm0** [comment] 2024-08-04 18:27
The error (pointer conversion) only occured with the base Termux setup. It didn't compile. And it errored both in gomobile and upstream mobile. So I think you're right and it is an upstream bug.

**Comment by vsm0** [comment] 2024-08-04 18:28
The error (pointer conversion) only occured with the base Termux setup. It didn't compile. And it errored both in gomobile and upstream mobile. So I think you're right and it is an upstream bug.

**Comment by hajimehoshi** [comment] 2024-08-04 18:30
> The error (pointer conversion) only occured with the base Termux setup. It didn't compile. And it errored both in gomobile and upstream mobile.

What command did you run actually?

**Comment by vsm0** [comment] 2024-08-04 18:35
I first created the main.go file
Then:

```bash
go mod init example
go mod tidy
go run .
```

Nothing special really.

**Comment by hajimehoshi** [comment] 2024-08-04 18:36
So this is not a test for gomobile, right?

**Comment by vsm0** [comment] 2024-08-04 18:45
It [the ebiten module] pulled in gomobile as a dependency, and the issue was in the android.c within gomobile/app/.
Again it's not specific to gomobile, since the issue was reproducible upstream.

**Comment by hajimehoshi** [comment] 2024-08-04 18:52
I'm confused. Is this issue reproducible with gomobile without ebitengine? What upstream did you mean?

**Comment by vsm0** [comment] 2024-08-04 18:56
Maybe I'm confused. How exactly is gomobile related to golang.org/x/mobile?

At first, the error came from gomobile as far as I could tell.

Then, as per your suggestion, I tried compiling an example from the mobile source. It was the base example, that draws something - independent of ebiten. The error was thus reproduced.

**Comment by hajimehoshi** [comment] 2024-08-04 19:02
> Maybe I'm confused. How exactly is gomobile related to golang.org/x/mobile?

gomobile is a tool in golang.org/x/mobile/cmd. Apparently you could reproduce the issue with the plain go-run, then you don't need to use it.

> Then, as per your suggestion, I tried compiling an example from the mobile source. It was the base example, that draws something - independent of ebiten. The error was thus reproduced.

Then, in https://github.com/golang/go/issues/68727, you could report the issue with a script to compile the gomobile example without your Ebitengine code, right?

**Comment by hajimehoshi** [comment] 2024-08-04 19:07
I'm gonna sleep soon. 

My current guess is that GOOS is android in Termux so there are some confusions in various libraries. Even if we could fix the egl issue, I'm not sure I could run an Ebitengine game since Termux doesn't seem to have X11.

**Comment by vsm0** [comment] 2024-08-04 19:08
> Then, in https://github.com/golang/go/issues/68727, you could report the issue with a script to compile the gomobile example without your Ebitengine code, right?

You mean change the issue content to be x/mobile specific? Yeah, ig. It would be the same script though, because all I did was go into the example directory and type _go run ._

**Comment by vsm0** [comment] 2024-08-04 19:12
> My current guess is that GOOS is android in Termux so there are some confusions in various libraries. Even if we could fix the egl issue, I'm not sure I could run an Ebitengine game since Termux doesn't seem to have X11.

It does have x11. The x11 problem was in the Ubuntu setup I added for a different test.

I can run x11 programs just fine. A gui, Java Swing, etc.

The fix _could_ be nothing more than adding a definition condition for Termux to follow the Termux patches, but anyway it's not that important (certainly not for such a long discussion lol)

> I'm gonna sleep soon

Same, it's like past 3:00 and I have class tomorrow :')

**Comment by hajimehoshi** [comment] 2024-08-04 19:21
The fix should not be so simple for Ebitengine since we would have to change Ebitengine to use Linux version even though GOOS=android.

Perhaps `GOOS=linux CGO_ENABLED=1 go run .` for your Ebitengine code might work. Please try tomorrow.

> You mean change the issue content to be x/mobile specific?

Nah, now I understand the situation more deeply, and Ebitengine should not use gomobile-related code for Termux. So this is not a gomobile issue as far as I understand. Sorry for going back and forth. 

Good night!

**Comment by vsm0** [comment] 2024-08-05 11:29
I revisited my Termux-Ubuntu setup, since it compiled successfully, and I have x11 configured right.

The aforementioned _main.go_ builds, but has a runtime error:

```bash
panic: gamepad: Stat failed: permission denied

goroutine 1 [running, locked to thread]:
main.main()
        /home/.../ebiten/main.go:32 +0x68
```

I was wondering if you have encountered this issue before, or if it would be possible for the time being to forego setting up gamepad for now, just to get something running

**Comment by hajimehoshi** [comment] 2024-08-05 12:05
I have never seen this error. We might be able to skip gamepad settings in this case, but we need more investigation.

**Comment by vsm0** [comment] 2024-08-06 21:52
Just an update of my experiments.
I can't seem to recall whether or not raylib-go actually worked [within standard Termux] before, but the latest I've tried fails to build with familiar errors:

```bash
./platforms/rcore_android.c:899:81: error: incompatible pointer to integer conversion passing 'ANativeWindow *' (aka 'struct ANativeWindow *') to parameter of type 'EGLNativeWindowType' (aka 'unsigned long') [-Wint-conversion]
../../../../usr/include/EGL/egl.h:136:109: note: passing argument to parameter 'win' here
In file included from rcore.c:508:
./platforms/rcore_android.c:963:97: error: incompatible pointer to integer conversion passing 'ANativeWindow *' (aka 'struct ANativeWindow *') to parameter of type 'EGLNativeWindowType' (aka 'unsigned long') [-Wint-conversion]
../../../../usr/include/EGL/egl.h:136:109: note: passing argument to parameter 'win' here
```

Pixel2 (by gen2brain) together with its opengl backend builds and runs fine, surprisingly enough. I wonder if their [gl] codebase is somehow more platform friendly or something. It'd be nice to maybe merge their implementation as a future goal, though I can't begin to imagine how much time/effort doing this would be, nor the legal details

**Comment by hajimehoshi** [comment] 2024-08-07 02:06
@vsm0 

Is it possible to patch this on your local Ebitengine and try whether it works?

```diff
diff --git a/internal/gamepad/gamepad_linux.go b/internal/gamepad/gamepad_linux.go
index d97d43970..17fd00a13 100644
--- a/internal/gamepad/gamepad_linux.go
+++ b/internal/gamepad/gamepad_linux.go
@@ -54,6 +54,9 @@ func (g *nativeGamepadsImpl) init(gamepads *gamepads) error {
                if err == unix.ENOENT {
                        return nil
                }
+               if err == unix.EPERM {
+                       return nil
+               }
                return fmt.Errorf("gamepad: Stat failed: %w", err)
        }
        if stat.Mode&unix.S_IFDIR == 0 {
```

**Comment by vsm0** [comment] 2024-08-07 08:45
It didn't work. This is how I applied the patch:
```bash
mkdir workspace
cd workspace
mkdir src
touch src/main.go
```
I wrote the aforementioned _main.go_ contents into src/main.go
```bash
cd src
go mod init src
go mod tidy
cd ..
gh repo clone hajimehoshi/ebiten
go work init ./src
go work use ./src
go work use ./ebiten
go work use ./ebiten/ebitenutil
```
Then I applied the patch to the clone.
```bash
go run -x .
```
The same error occurs.
I know for a fact that my workspace and patch are set up correctly since I added a print statement to the erroring code, just to make sure it was running the local modified repo, not the original:
```bash
BECAUSE I AM HERE
panic: gamepad: Stat failed: permission denied                        
goroutine 1 [running, locked to thread]:
main.main()
        /data/data/com.termux/files/home/prog/go/workspace/src/main.go:32 +0x68                                                             exit status 2
```

**Comment by hajimehoshi** [comment] 2024-08-07 09:11
> BECAUSE I AM HERE

Where did you add this?

**Comment by vsm0** [comment] 2024-08-07 09:50
> > BECAUSE I AM HERE
> 
> Where did you add this?

At the top of the patched error checking, before all the if statements.

It [the message] wasn't really to check what the value of the error was, but to acertain the build was pulling from the local repo version not the go cache or github.

```bash
func (g *nativeGamepadsImpl) init(gamepads *gamepads) error {
        // Check the existence of the directory `dirName`.
        var stat unix.Stat_t
        if err := unix.Stat(dirName, &stat); err != nil {
                fmt.Println("BECAUSE I AM HERE")
                if err == unix.ENOENT {
                        return nil
                }
                if err == unix.EPERM {
                        return nil
                }
                return fmt.Errorf("gamepad: Stat failed: %w", err)
  }
```

**Comment by hajimehoshi** [comment] 2024-08-07 09:57
OK. Apparently, the error "permission denied" is `EACCES`, not `EPERM` What about this?

```diff
diff --git a/internal/gamepad/gamepad_linux.go b/internal/gamepad/gamepad_linux.go
index d97d43970..17fd00a13 100644
--- a/internal/gamepad/gamepad_linux.go
+++ b/internal/gamepad/gamepad_linux.go
@@ -54,6 +54,9 @@ func (g *nativeGamepadsImpl) init(gamepads *gamepads) error {
                if err == unix.ENOENT {
                        return nil
                }
+               if err == unix.EACCES {
+                       return nil
+               }
                return fmt.Errorf("gamepad: Stat failed: %w", err)
        }
        if stat.Mode&unix.S_IFDIR == 0 {
```

**Comment by vsm0** [comment] 2024-08-07 10:27
![Screenshot_20240807-182658.png](https://github.com/user-attachments/assets/8098a801-4dee-4ac3-a29c-4a3dd1d11c7f)

:)

**Comment by hajimehoshi** [comment] 2024-08-07 14:57
As `/dev/input` is not accessible in your environment, is it possible to use inputs like keyboards?

**Comment by vsm0** [comment] 2024-08-07 21:47
Yes, keyboard input does work, even for ebiten.

The Android soft keyboard doesn't provide a sustained press (for checks like ebiten.IsKeyPressed) so the behavior is like IsJustPressed.

The best option is an external keyboard, although back when I was developing using other frameworks I just installed a game keyboard that simulated the expected sustained press.

**Comment by hajimehoshi** [comment] 2024-08-08 02:37
Thanks. Apparently the keyboard inputs don't have anything to do with `/dev/input`.

I've update Ebitengine. If there is no other problem, can we close this issue as solved?

**Comment by vsm0** [comment] 2024-08-08 04:19
As per the title now, yeah I guess. Again, thanks for the help.

Termux development isn't the best right now, but it's nice that I get to test Ebiten and other frameworks without a computer at hand.

**Closed** 2024-08-08 04:19 UTC
Labels: bug, os:linux, os:android

**Comment by Anonymous941** [comment] 2026-07-07 23:26
Any workaround?

**Comment by hajimehoshi** [comment] 2026-07-08 03:01
If you have an issue, please file it, thanks
