### ISSUE TITLE
internal/graphicsdriver/opengl: creating framebuffer fails w/ an error 36054 on OpenGL

### ISSUE THREAD

**Issue by erexo** [hajimehoshi/ebiten#2486] opened 2022-12-06 20:06 UTC
### Ebitengine Version

760e6b9ebd228554bed191410ce47d8a93a329dd

### Operating System

- [X] Windows
- [ ] macOS
- [ ] Linux
- [ ] FreeBSD
- [ ] OpenBSD
- [ ] Android
- [ ] iOS
- [ ] Nintendo Switch
- [ ] Xbox
- [ ] Web Browsers

### Go Version (`go version`)

1.19.1

### What steps will reproduce the problem?

One of my players' game is unexpectedly closing during playing (and at random time) with error:
`opengl: creating framebuffer failed: 36054`.
She claims that she's using DirectX but the error seems to be opengl related so probably ebitengine decided that fallback from directx is necessary. She also claims that the error is random. Sometimes it's once per day, sometimes its 4 times per day.
`dxdiag`:
![image](https://user-images.githubusercontent.com/6548968/206011540-2799e85c-3cc2-4fed-a17b-e12b9412ebcf.png)
![image](https://user-images.githubusercontent.com/6548968/206011556-8e3dbfb5-1665-49ab-b9d0-8ca663cc3f1b.png)

### What is the expected result?

`ebiten.RunGame` does not throw an error, and maybe no fallback from DirectX to OpenGL

### What happens instead?

`ebiten.RunGame` throws an error

**Comment by hajimehoshi** [comment] 2022-12-07 03:47
> She claims that she's using DirectX but the error seems to be opengl related so probably ebitengine decided that fallback from directx is necessary. She also claims that the error is random. Sometimes it's once per day, sometimes its 4 times per day.

As the feature level 12 is not supported, Ebitengine should use OpenGL in this machine.

**Comment by erexo** [comment] 2022-12-07 11:13
Can we please do something about it? There are lots and lots of players who for various reasons are unable to reach such feature level and I absolutely hate to tell people that despite having 2d pixel game they are unable to play it.

**Comment by hajimehoshi** [comment] 2022-12-07 11:28
You can choose feature level by setting an environment variable `EBITENGINE_DIRECTX_FEATURE_LEVEL=11_0` (https://github.com/hajimehoshi/ebiten/issues/2466) to force to use DirectX.

> Can we please do something about it?

Unfortunately I cannot guarantee that I can fix this issue.

**Comment by erexo** [comment] 2022-12-07 11:30
Again with the env variables? What should I do? Check in the game "if dx12 feature level < 12 then set env to 11_0"? That sounds truly ridiculous to make the game creator responsible for such things

**Comment by hajimehoshi** [comment] 2022-12-07 11:31
> Again with the env variables? What should I do? Check in the game "if dx12 feature level < 12 then set env to 11_0"? That sounds truly ridiculous to make the game creator responsible for such things

Yes, again. You can set the variable in your program as you have already done for EBITENGINE_GRAPHICS_LIBRARY.

I plan to add RunGamWithOptions but please wait for it.

> That sounds truly ridiculous to make the game creator responsible for such things

:-/

**Comment by erexo** [comment] 2022-12-07 11:54
It's not "configuring the graphics library" you are talking about, it's "disabling the primary graphics library by default to many users and if you want to enable it set the env variable but you can't be really sure if the lib is actually available or not" thing.
I'm kinda upset because I was alarming so, so, sooo many times about usability of adding explicit and easy option to set the graphics library and you was so against it "because ebitengine should know better". And now I'm hearing that the same ebitengine is disabling directx for players who actually have compatible dx but with lower feature level, and ebitengine could work on such machine but just decided not to. This results in players with decent machines not being able to play AT ALL because ebitengine in it's smartness decided that there is no compatible game library (unless you, the game creator who should not touch such configs decide, via env variable for some reason, that ebitengine should use featurelevel 11 instead of 12).
On one hand you are strongly in favor of not touching such settings and letting ebitengine decide, and I don't agree with that but I was able to tolerate it as long as players were able to play. But the current state is "I as a game dev must explicitly set the dx featurelevel and kinda guess which featurelevel is available on given machine or otherwise players may not be able to play my game", and that's ridiculous.

`RunGameWithOptions` is an absolute must in current situation where ebitengine can be clearly wrong.
What I would like to be able to do is to specify which lib should be used first (directx/opengl), and if that primary lib is not available for some reason then fallback to the other lib (so that player can decide whether to use dx or opengl, and if his/her lib of choice is not available then silently fallback to the other). And I would like to not care about dx featurelevels. If player decided to use DirectX and has compatible dx that can be handled by ebitengine and if the game actually executes on dx, he/she should be able to play on that dx, regardless of version or/and featurelevels. If ebitengine supports it it should support run it.

**Comment by hajimehoshi** [comment] 2022-12-07 12:06
By the way, in general, this error causes due to short of memory. My guess is that your game makes too many images or framebuffers. You can check this with `-tags=ebitenginedebug`.

> I'm kinda upset because I was alarming so, so, sooo many times about usability of adding explicit and easy option to set the graphics library and you was so against it "because ebitengine should know better".

So I was convinced to add RunGameWithOptions as the real world is harder than I expected, thanks to your recent many reports. Without them, I was not sure what is right.

I'll be working on this later, but I don't have infinite bandwidth unfortunately. Do not forget that this is just an OSS made with my spare time, not a commercial ware.

>  And now I'm hearing that the same ebitengine is disabling directx for players who actually have compatible dx but with lower feature level, and ebitengine could work on such machine but just decided not to. This results in players with decent machines not being able to play AT ALL because ebitengine in it's smartness decided that there is no compatible game library (unless you, the game creator who should not touch such configs decide, via env variable for some reason, that ebitengine should use featurelevel 11 instead of 12).

Actually there is a machine that DirectX doesn't work well with the feature level 11. (https://github.com/hajimehoshi/ebiten/issues/2447) Do you have any other suggestion to fix #2447 and this issue at the same time? I think giving an option to configure this is the best way so far.

> What I would like to be able to do is to specify which lib should be used first (directx/opengl), and if that primary lib is not available for some reason then fallback to the other lib (so that player can decide whether to use dx or opengl, and if his/her lib of choice is not available then silently fallback to the other). And I would like to not care about dx featurelevels. 

The problem is that a problem can occur AFTER the graphics library (and its feature level) is determined and initialization itself succeeds. In this case, we cannot fallback to other libraries. This OpenGL issue is actually the case.

**Comment by erexo** [comment] 2022-12-07 12:12
What about leaving `EBITENGINE_DIRECTX_FEATURE_LEVEL` for special cases like #2447, but when this env is not set then just use latest available feature level instead of hardlocking on 12_0 and disallow any other?

**Comment by hajimehoshi** [comment] 2022-12-07 12:14
> What about leaving EBITENGINE_DIRECTX_FEATURE_LEVEL for special cases like https://github.com/hajimehoshi/ebiten/issues/2447, but when this env is not set then just use latest available feature level instead of hardlocking on 12_0 and disallow any other?

I was just thinking about that. This might make sense. Actually when #2447 was fixed, I fixed #2459 at the same time, so I'm not 100% confident #2447 was the true fix for their machine. OK, I'm fine to change the default to 11_0.

**Comment by hajimehoshi** [comment] 2022-12-07 12:19
So, thought the OpenGL issue is not fixed (I don't think this is fixable), was your issue resolved by using the feature level 11?

**Comment by erexo** [comment] 2022-12-07 12:30
I can't really tell because I don't really have contact with this player anymore

**Comment by hajimehoshi** [comment] 2022-12-07 12:32
That's unfortunate.

I'll mark this issue as fixed as there is no action item I can take.

I recommend checking how many images (textures) are used in your game. My guess is a little too many.

**Closed by hajimehoshi** 2022-12-07 12:32 UTC
Labels: bug, os:windows

**Comment by hajimehoshi** [comment] 2023-03-01 17:31
As #2581 was fixed, the situation might be improved.
