### ISSUE TITLE
OpenGL on Windows: vsync off only works in fullscreen mode

### ISSUE THREAD

**Issue by harbdog** [hajimehoshi/ebiten#2662] opened 2023-05-06 03:26 UTC
### Ebitengine Version

2.5.2

### Operating System

- [X] Windows
- [ ] macOS
- [ ] Linux
- [ ] FreeBSD
- [ ] OpenBSD
- [ ] Android
- [ ] iOS
- [ ] Nintendo Switch
- [ ] Xbox
- [ ] Web Browsers

### Go Version (`go version`)

1.19.6

### What steps will reproduce the problem?

In windows 10 using directx note that turning off vsync works as expected for both windowed and fullscreen applications.

Then force opengl by setting the environment variable `EBITENGINE_GRAPHICS_LIBRARY=opengl`, note that in full screen with vsync off works as expected with FPS over 60, but during windowed mode it gets capped at 60.

### What is the expected result?

vsync should be off even for windowed not just fullscreen

### What happens instead?

windowed is being capped at 60 FPS

**Comment by hajimehoshi** [comment] 2023-05-06 03:32
I couldn't reproduce the issue. My guess is that this is due to your OpenGL driver, but I am not 100% sure.

What is your machine's graphics card?

**Comment by harbdog** [comment] 2023-05-06 03:34
RTX 3080 with latest drivers. The good news is that the opengl performance when in fullscreen is so much better than directx, just odd that the windowed mode is doing that.

**Comment by harbdog** [comment] 2023-05-06 03:38
I decided to play with the NVIDIA Control Panel and found that the refresh rate in the Display -> Change resolution screen was set to Refresh rate of 60Hz. Changing that to 100Hz saw a corresponding change in the windowed FPS cap to 100. So I guess that is somehow just tied to the windows refresh rate even though directx is not.

**Comment by harbdog** [comment] 2023-05-06 03:40
Another observation, when my focus leaves the windowed game running, the FPS goes up to what I see in fullscreen (120FPS), but then as soon as I bring focus back to the game it pops back to that 100 FPS (or 60 when set to 60Hz).

**Comment by hajimehoshi** [comment] 2023-05-06 06:00
>  Changing that to 100Hz saw a corresponding change in the windowed FPS cap to 100.

OK, so this sounds like a setting issue in a graphics card, rather than Ebitengine. I don't think there is an action item for this issue. Let me close this.

**Closed by hajimehoshi** 2023-05-06 06:00 UTC
Labels: bug, os:windows
