### ISSUE TITLE
windows: Crash at launching

### ISSUE THREAD

**Issue by hajimehoshi** [hajimehoshi/ebiten#836] opened 2019-03-28 14:48 UTC
Borja Clemente reported:

```
panic: winmm error at waveOutOpen: WAVEERR_BADFORMAT
```

 Windows 10 (64bit, intel i7 processor)

**Comment by clebs** [comment] 2019-03-28 14:52
Further details:
- After opening it several times in a row eventually it works.
- Happens for both 386 and amd64 binaries.
- Happens on both intel and AMD processors.
- Build commands used:
`CGO_ENABLED=0 GOOS=windows GOARCH=amd64 go build -o game-win64.exe`
`CGO_ENABLED=0 GOOS=windows GOARCH=386 go build -o game-win32.exe`

**Comment by clebs** [comment] 2019-03-29 17:19
Just tested on a Virtualbox Windows 10 VM with the same error.

**Comment by hajimehoshi** [comment] 2019-03-30 09:29
I think there is an issue in your audio device (that is used by both your host machine and VM). I am not sure.

> The error does not come from the game loop function, I wrapped all errors returned with context to better trace them. This error comes directly from the ebiten RUN func.

The low-layer device is created and initialized lazily, and Run initializes the device.

**Comment by clebs** [comment] 2019-03-30 14:14
I tested in 3 different machines with the same result:
- Windows 10 PC with Intel processor
- Windows 10 PC with AMD processor
- MacBook Pro 2014 with Windows 10 VM

I am still trying to reproduce this with a minimal example.

**Comment by hajimehoshi** [comment] 2019-03-30 15:12
Oh that's interesting... Thank you for testing.

**Comment by hajimehoshi** [comment] 2019-03-30 17:12
So the audio device should not matter. I'm looking forward the minimal example to reproduce this issue.

**Comment by clebs** [comment] 2019-03-31 13:53
Hello again,
I finally found the root cause of the issue:
- It happens when creating several players with the same audio file, for example different entities that use the same sound effect.

I also have created an example project to reproduce it. How can I send it to you @hajimehoshi?
Thanks!

**Comment by hajimehoshi** [comment] 2019-03-31 14:51
Hi, thank you for investigating!

> It happens when creating several players with the same audio file, for example different entities that use the same sound effect.

As `io.Reader` should not be shared by multiple players, you'd need to create players from bytes instead of `io.Reader`:

https://godoc.org/github.com/hajimehoshi/ebiten/audio#NewPlayer
> Note that the given src can't be shared with other Player objects.

I'm not sure why the lower device complains in such situation, but I think I can create a better error message.

> I also have created an example project to reproduce it. How can I send it to you @hajimehoshi?
Thanks!

I appreciate it! Could you mail to hajimehoshi@gmail.com, or share that on GitHub or something?

**Comment by clebs** [comment] 2019-04-01 07:25
Hi,
Hmmm... I do create a new reader every time I create a player by using ebiten's `audio.BytesReadSeekCloser()`.
In the example I sent, you can see exactly how I create players, so maybe you see what I am doing wrong.

It is also strange that on mac OS X and Linux this is not a problem.

Thanks for looking into it.

**Comment by hajimehoshi** [comment] 2019-04-02 14:26
I think this was fixed by https://github.com/hajimehoshi/oto/issues/73

**Comment by hajimehoshi** [comment] 2019-04-02 14:36
I let this issue open until releasing a new version of Oto and cherry-picking the fix onto 1.9 branch.

**Comment by clebs** [comment] 2019-04-02 18:17
Tested again in different Windows machines and it fixed in all of them!

**Closed** 2019-04-09 23:43 UTC
Labels: bug, os:windows
