### ISSUE TITLE
Vibrations during resize, ebiten 2.1.0-rc1

### ISSUE THREAD

**Issue by sedyh** [hajimehoshi/ebiten#1617] opened 2021-04-22 16:56 UTC
https://user-images.githubusercontent.com/19890545/115754284-b5809900-a3a4-11eb-8bd7-a772ce6920bf.mp4

Encountered strange resizing glitch in 2.1.0-rc1. Resizing on stable version (2.0.8) is working good.

**Comment by hajimehoshi** [comment] 2021-04-22 17:03
What environment are you using? Thanks!

**Comment by sedyh** [comment] 2021-04-22 17:05
Hello. This is my current enviroment:
![image](https://user-images.githubusercontent.com/19890545/115755476-0fce2980-a3a6-11eb-9cc7-d5220c294a94.png)

**Comment by hajimehoshi** [comment] 2021-04-22 17:17
I could not reproduce this. Did you adjust 'fractional scaling' on your display?

**Comment by sedyh** [comment] 2021-04-22 17:27
Well, i don't even have scaling option in layout tab (as far as I know, fractional scaling was added in linux mint 20). But UI scaling is set to "auto".
![image](https://user-images.githubusercontent.com/19890545/115759428-e5ca3680-a3a8-11eb-9f87-36a1673060c5.png)

**Comment by hajimehoshi** [comment] 2021-04-22 18:18
Thanks.

As this is also related to APIs to adjust the window size, I hope the same fix https://github.com/hajimehoshi/ebiten/issues/1618#issuecomment-825070035 would be applied.

**Comment by sedyh** [comment] 2021-04-23 13:37
Vibrations are gone after `b726d19`, but something strange was happened. i described it in #1618

**Comment by hajimehoshi** [comment] 2021-04-23 13:38
Thanks!

Fixed by https://github.com/hajimehoshi/ebiten/commit/d446aa39a96a7498cdfaadfc7debaaf4c47b1414

**Closed by hajimehoshi** 2021-04-23 13:38 UTC
Labels: bug, os:linux
