### ISSUE TITLE
Weird rendering with <=1 scale

### ISSUE THREAD

**Issue by lei-cao** [hajimehoshi/ebiten#669] opened 2018-08-21 07:53 UTC
Hi 
I am using Ebiten for making some algorithm visual game here https://github.com/lei-cao/programming/tree/master/code/algoman

It displays some random but triangle shifting scratches like this when I am using scale 1 when calling `ebiten.Run`
![image](https://user-images.githubusercontent.com/136104/44388452-b9581f80-a55a-11e8-9c74-d39b725f5cb5.png)

well, just by changing the scale to any value bigger than one, 1.1 for instance, it became normal.
![image](https://user-images.githubusercontent.com/136104/44388171-07205800-a55a-11e8-9ad3-9d1510ce1d04.png)

It might be some logic issue in my code but I am struggling to figure it out. So I am creating this issue for getting more inputs.

**Comment by hajimehoshi** [comment] 2018-08-21 08:16
Thank you for reporting. I'll take a look later.

**Comment by hajimehoshi** [comment] 2018-08-21 08:17
What environment does this problem happen?

**Comment by lei-cao** [comment] 2018-08-21 10:51
hi @hajimehoshi ,

It's actually another issue related to external monitors. https://github.com/hajimehoshi/ebiten/issues/668 , 
If I built it with go run main.go on my mac main monitor, it shows normally. 
If I built it from terminal from external monitor, it shows the shifting. 

If I use gopherjs serve, and then visit it from browser, in mac monitor, it's normal. in external monitor, it shows the shifting.

**Comment by hajimehoshi** [comment] 2018-08-21 10:57
That's interesting. Do these monitors different resolution? Retina or not Retina? Thanks!

**Comment by lei-cao** [comment] 2018-08-21 10:59
the external monitor is not retina.
![image](https://user-images.githubusercontent.com/136104/44397849-4d82b080-a574-11e8-8706-5d3fe149303c.png)

**Comment by hajimehoshi** [comment] 2018-08-28 16:35
Confirmed that this happened with <1 scale:

![screenshot](https://user-images.githubusercontent.com/16950/44736999-c44b1b00-ab2b-11e8-95f5-a2e98f719a0b.png)

**Comment by hajimehoshi** [comment] 2018-08-28 17:53
Note that this problem happens when the *actual scale is 1 (e.g. in Retina display, this problem happens when the scale passed to `Run` is equal to or less than 0.5 since the scale is doubled internally at Retina).

**Comment by hajimehoshi** [comment] 2018-08-28 18:27
```diff
diff --git a/internal/graphics/shader.go b/internal/graphics/shader.go
index 3b27b559..51d0c4f3 100644
--- a/internal/graphics/shader.go
+++ b/internal/graphics/shader.go
@@ -142,8 +142,11 @@ void main(void) {
 #endif
 
 #if defined(FILTER_SCREEN)
-  highp vec2 p0 = pos - texel_size / 2.0 / scale;
-  highp vec2 p1 = pos + texel_size / 2.0 / scale;
+  // It looks like that jaggy can happen when scale = 1 without adjusting.
+  // Add 1/512 scaled texel size to avoid jaggy (#669)
+  highp vec2 adjust = texel_size / 512.0 / scale;
+  highp vec2 p0 = pos - texel_size / 2.0 / scale + adjust;
+  highp vec2 p1 = pos + texel_size / 2.0 / scale - adjust;
 
   vec4 c0 = texture2D(texture, p0);
   vec4 c1 = texture2D(texture, vec2(p1.x, p0.y));
```

This diff fixes this problem, but this is very ad-hoc.

**Comment by hajimehoshi** [comment] 2018-08-29 15:17
I think this has been fixed.

@lei-cao Could you test this? Thank you!

**Comment by hajimehoshi** [comment] 2018-09-02 15:47
Let me close this. Feel free to reopen this when you find any problems.

**Closed by hajimehoshi** 2018-09-02 15:47 UTC
Labels: bug, os:macos
