### ISSUE TITLE
Titlebar is opened off-screen when running on Windows.

### ISSUE THREAD

**Issue by Splizard** [hajimehoshi/ebiten#328] opened 2017-02-23 01:46 UTC
This is really annoying.. anyway to fix it? I have to keep shift-clicking on the taskbar icon and then clicking on move followed by pressing the arrowkeys.

**Comment by Splizard** [comment] 2017-02-23 01:55
This needs to be added to the SetScale function of ui_glfw.go
```
m := glfw.GetPrimaryMonitor()
v := m.GetVideoMode()
w, h := u.glfwSize()
x := (v.Width - w) / 2
y := (v.Height - h) / 3
u.window.SetPos(x, y)
```

**Comment by hajimehoshi** [comment] 2017-02-23 02:54
Thank you for reporting, but I don't understand the situation. What does "Titlebar is opened off-screen" mean? Could you elaborate more what is happening?

**Comment by Splizard** [comment] 2017-02-23 06:36
Hope this image can be of some help :)
![Uploading Bug.png…]()

**Comment by hajimehoshi** [comment] 2017-02-23 06:38
That's interesting. Thank you for explanation. I've never seen such problem on my Windows machine. Do you have a code snippet to reproduce this? SetScreenSize should be called to do that, maybe?

**Comment by Splizard** [comment] 2017-02-23 06:40
Anything that calls ebiten.SetScreenScale(x)
will reproduce this behaviour from what I have noticed.

**Comment by hajimehoshi** [comment] 2017-02-23 13:47
That's odd, I couldn't reproduce this on examples/windowsize

**Comment by Splizard** [comment] 2017-02-23 20:09
I was testing on a Windows 10 system at the time. I don't know why it wouldn't be reproducible.

**Comment by hajimehoshi** [comment] 2017-02-24 13:24
How about `SetScreenSize` instead of `SetScreenScale`? Both implementations have common part so it would make sense if `SetScreenSize` has the same problem.

**Comment by hajimehoshi** [comment] 2017-02-24 14:44
https://github.com/go-gl/glfw/blob/master/v3.2/glfw/glfw/src/win32_window.c#L1147

As changing screen size/scale calls `_glfwPlatformSetWindowSize`, I investigated that function and found that `SWP_NOMOVE` is indicated. The window position should never be changed. What kind of machine do you use?

**Comment by Splizard** [comment] 2017-02-24 22:16
I will let you know when I get the chance to use the affected PC again

**Comment by hajimehoshi** [comment] 2017-04-18 02:12
ping @Splizard , what is going on this?

**Comment by Splizard** [comment] 2017-04-18 07:11
A friend of mine compiled a recent version of ebiten on his Windows 10 machine and the problem persists as far as I am aware.

**Comment by hajimehoshi** [comment] 2017-04-18 07:38
Thanks, and I'd like to know the environment e.g. how many displays or what kind of machine he/she is using.

**Comment by Splizard** [comment] 2017-04-18 11:49
It has been tested on both a Desktop machine and a laptop machine running on windows 10, a single screen.

**Comment by hajimehoshi** [comment] 2017-04-18 15:27
OK, thanks. The number of displays is very important information. I still can't reproduce this, but as only one display causes this error, my guess is that glfwGetVideoMode fails to return valid width/height. I'll try to add a hack in that case.

**Comment by hajimehoshi** [comment] 2017-04-18 15:52
@Splizard I'd be happy if you and your friend could update Ebiten and test it. Thanks!

**Comment by hajimehoshi** [comment] 2017-05-13 06:14
ping @Splizard

**Comment by Splizard** [comment] 2017-05-14 06:18
I don't have any windows machines handy unfortunately :/

**Comment by hajimehoshi** [comment] 2017-05-14 06:45
OK, it seems hard to reproduce this, and I think I could add an ad-hoc fix. Let me close this.

**Closed by hajimehoshi** 2017-05-14 06:45 UTC
Labels: bug, os:windows
