### ISSUE TITLE
Ebiten skips drawing SubImages of 1 pixel width if the Y Scale is < 0.25

### ISSUE THREAD

**Issue by harbdog** [hajimehoshi/ebiten#839] opened 2019-04-06 18:41 UTC
I'm trying to use Ebiten to create a raycaster game and found that my distant textures aren't being rendered until I get closer to them. [In my stackoverflow question](https://stackoverflow.com/questions/55506591/how-do-i-increase-the-raycast-render-distance?noredirect=1) I asked since I wasn't sure if it was a bug in the raycasting method or not, I ultimately found the exact reproducible problem:

First take someImage and take a SubImage of it with a pixel width of 1, but a normal height, e.g.:
```
thisRect := image.Rect(15, 5, 16, 250)
myImage := someImage.SubImage(thisRect).(*ebiten.Image)
```

Next, scale just the Y to make it smaller and draw it:
```
op.GeoM.Scale(1.0, 0.25)
screen.DrawImage(myImage, op)
```

In that case you should see a small vertical 1 pixel width strip of the image. But, now reduce the Y scale below 0.25. 
```
op.GeoM.Scale(1.0, 0.24)
screen.DrawImage(myImage, op)
```

The strip doesn't draw at all! 

But it will draw at a Y scale less than 0.25 if the pixel width is 2 or more:
```
thisRect := image.Rect(15, 5, 17, 250)
```

So the question is whether the Ebiten scale rendering code can be adjusted to allow a pixel width of 1 to scale smaller than 0.25.

**Comment by hajimehoshi** [comment] 2019-04-06 19:58
Hi, thank you for using Ebiten!

Unfortunately, such edge cases like rendering images with less-than-1-pixel scale depend on graphics drivers, so there is no guarantee about deterministic behavior. Thus, I'm afraid I probably cannot say the cause.

**Comment by hajimehoshi** [comment] 2019-04-06 19:59
What about rendering with linear filter?

**Comment by hajimehoshi** [comment] 2019-04-06 20:06
Oops sorry this is my misunderstanding, width is 1px but only Y is scaled?

Let me try, but could you give me a minimum code to reproduce this issue if possible? Thanks!

**Comment by harbdog** [comment] 2019-04-06 20:28
Here's a gist where I started with your highDPI example and made modifications, just tweak the values I mentioned in the issue description to see what I'm seeing.

https://gist.github.com/harbdog/075c527eb43df72fb2bd2657199185f1

**Comment by hajimehoshi** [comment] 2019-04-06 20:31
OK so the cause was the mipmap selection: if the determinant of the geometry matrix is small, mipmap is used, but in your case, the mipmap level is so high that the image width becomes 0.

I think this was fixed in the latest Ebiten.

**Comment by hajimehoshi** [comment] 2019-04-06 20:35
> Here's a gist where I started with your highDPI example and made modifications, just tweak the values I mentioned in the issue description to see what I'm seeing.

Thanks! I could reproduce this without the fix (3cb9d18), and confirmed this doesn't happen with the fix.

**Closed by hajimehoshi** 2019-04-06 20:35 UTC
Labels: bug, question

**Comment by harbdog** [comment] 2019-04-06 21:39
Confirmed! Updated with `go get -u github.com/hajimehoshi/ebiten/...` and now have good rendering!

https://github.com/harbdog/raycaster-go
![raycast-success](https://user-images.githubusercontent.com/1300522/55675577-d09e1000-5892-11e9-9d08-5e24c3fe905b.png)

**Comment by hajimehoshi** [comment] 2019-04-07 21:17
I'm glad to hear that. Thank you for reporting! Your game screenshot looks great!
