### ISSUE TITLE
Screen artifacting while game running

### ISSUE THREAD

**Issue by venning** [hajimehoshi/ebiten#2106] opened 2022-05-27 14:04 UTC
I've noticed that when I have an Ebiten game running, I see visible distortions and artifacting on my laptop monitor screen outside of the running game, to include on other Workspaces. This can also affect the external monitor (which is not running the game).

Things like blue lines running horizontally through the screen and all open windows, or the toolbar at the top of the screen having its inner third overwritten by blue artifacts. It's the kind of thing that looks like the monitor is failing. The artifacts only last for a fraction of a second, and always within the first few seconds of starting the game.

I've never seen this before with any other application. Is this a known issue?

(Macbook Pro; OS X 11.6.5; Intel Iris Pro; Ebitengine 2.3.2)

**Comment by hajimehoshi** [comment] 2022-05-27 14:05
I have not seen this issue, but this might happen due to GPU usages by Ebitengine.

I appreciate a screenshot. Thanks,

**Comment by venning** [comment] 2022-05-27 14:51
I attempted unsuccessfully to record the artifacting.  Each time, it became less constant and took longer to appear.  Gyazo did not have a long enough recording window for me to catch the problem.

Then I tried Quicktime.  The problem occurred while I was recording the screen, but the recording did not show it.  I assume that is relevant.  However the screen capture works, it is at a higher level than the actual display output.

By the time I decided to record with my phone, the error had stopped and I wasn't able to capture it. :(

If I see it again, I will try to record it on my phone and follow up here.

**Comment by mikenye** [comment] 2022-05-28 11:23
@venning 

I’ve seen this as well but thought it might just be my old MacBook dying…

I’ll try and record it. 

Out of interest what make/model is your MBP?

**Comment by tinne26** [comment] 2022-07-02 10:58
I also experienced some flickering on Linux, but I had it happen even with glfw alone (so, not an Ebitengine issue). MacOS is a whole different story, but I think it's worth testing a glfw program directly to confirm that the issue doesn't also happen there for macOS. For example, I was recently using [this code to test mouse movement](https://gist.github.com/tinne26/8d760c8798207e76530630be6351d121) and had some background flickering on the terminal from which I launched the program.

**Comment by hajimehoshi** [comment] 2022-07-02 14:24
Perhaps #2106?

**Comment by venning** [comment] 2022-07-03 02:46
(Not sure which issue to respond to.) I also saw the flashing with Bindless, but not with hajimehoshi's [test case](https://github.com/hajimehoshi/ebiten/issues/2174#issuecomment-1172868389). It was different that the blue artifacting I experienced with this issue.

Since creating this issue, I have upgraded my OS to Monterey as, apparently, Big Sur is known for GPU issues. (I had only upgraded to Big Sur to install the command line tools necessary for Ebiten, so I only had that for a couple of weeks.)

**Comment by hajimehoshi** [comment] 2022-07-03 07:07
> Since creating this issue, I have upgraded my OS to Monterey as, apparently, Big Sur is known for GPU issues. (I had only upgraded to Big Sur to install the command line tools necessary for Ebiten, so I only had that for a couple of weeks.)

I see. Actually I have found suspicious behaviors in Metal drivers, so I understand your situation could usually happen, though I could not reproduce your issue yet.

I added some fixes for #2154. I'm not sure this is related to your issue, but could you try the latest version?

```
go get github.com/hajimehoshi/ebiten/v2@c31cc4ecffca2657444e50716d638f3ebbf84ad3
```

Thanks,

**Comment by venning** [comment] 2022-07-03 14:07
> could you try the latest version?

I'm assuming you mean to try the [test case](https://github.com/hajimehoshi/ebiten/issues/2154#issue-1275841483) from #2154. I did so with the Ebiten version you listed and still got an error, after 4 tries:

<img width="332" alt="Screen Shot 2022-07-03 at 10 04 36 AM" src="https://user-images.githubusercontent.com/3902717/177043463-44921e9d-d17c-4620-98ad-fa1bad1f0683.png">

If you mean the blue artifacting, I'm not sure how to provoke that and have not seen it since the day I originally created this issue. (There's a good chance it was Big Sur's fault.)

**Comment by venning** [comment] 2022-07-03 14:12
As a side note, is there an Ebiten API method that returns the current graphics library? I didn't see one that was exposed outside of `/internal`.

I don't know if it would be helpful outside of tracking down issues like this, but I've found myself using `EBITEN_GRAPHICS_LIBRARY` on every run since the system seems to switch between OpenGL and Metal depending on whether or not I have an external monitor attached. It's not a big deal, but I could see it be useful in debugging.

**Comment by hajimehoshi** [comment] 2022-07-03 14:44
> I did so with the Ebiten version you listed and still got an error, after 4 tries:

Ugh, #2154 was not fixed yet...?

> If you mean the blue artifacting, I'm not sure how to provoke that and have not seen it since the day I originally created this issue. (There's a good chance it was Big Sur's fault.)

Actually I meant this (in this issue). If you don't see this recently, we can close this.

> As a side note, is there an Ebiten API method that returns the current graphics library?

There is not, but I think you are using Metal. I'll consider to create that.

**Comment by hajimehoshi** [comment] 2022-07-03 14:50
OK let's close this. Let's revisit when you find the same blue-artifact issue again.

**Closed by hajimehoshi** 2022-07-03 14:50 UTC
Labels: bug, os:macos, help-wanted, needs-investigation
