### ISSUE TITLE
text: Need assistance putting text in box

### ISSUE THREAD

**Issue by SamusAranX** [hajimehoshi/ebiten#1406] opened 2020-10-27 02:41 UTC
As far as I can tell, the change from `MeasureString` to `BoundString` made it impossible to do anything precise with the returned values. I need pixel precise values to be able to accurately position text on a small canvas (320x240 pixels), but it's just not possible.

I have prepared a small-ish test project that demonstrates this. There's a bunch of setup code that you can ignore, the important part is in `screens/testscreen.go`: [ebitenBoundString.zip](https://github.com/hajimehoshi/ebiten/files/5442528/ebitenBoundString.zip)

I wrote this method to try to draw text in a box:
```go
func DrawTextInBox(dst *ebiten.Image, str string, face font.Face, x, y int) image.Point {
	bounds := text.BoundString(face, str)

	boundsX, boundsY := float64(x), float64(y)
	boundsW, boundsH := float64(bounds.Max.X - bounds.Min.X), float64(bounds.Max.Y - bounds.Min.Y)

	faceMetrics := face.Metrics()
	mHeight := faceMetrics.Height.Round()

	ebitenutil.DrawRect(dst, boundsX, boundsY, boundsW, boundsH, color.Black)
	text.Draw(dst, str, face, x, y + mHeight, color.White)

	return image.Point{
		X: bounds.Dx(),
		Y: bounds.Dy(),
	}
}
```

The result is this:
![image](https://user-images.githubusercontent.com/676069/97249488-3d298880-1804-11eb-9b68-dfcf915dbb5f.png)

As you can see from the code, I'm already compensating for the dot position thingy, but it's not enough. The text is misaligned on the vertical axis anyway.  How can I properly align the text with the box without relying on font-specific magic numbers? I need this to work with arbitrary fonts and font sizes.

**Comment by hajimehoshi** [comment] 2020-10-27 03:43
Hi, would it be possible to give me a minimized example to reproduce the issue? Thanks

**Comment by hajimehoshi** [comment] 2020-10-27 03:47
NVM, now I could download the project.

**Comment by hajimehoshi** [comment] 2020-10-27 03:57
> `faceMetrics.Height.Round()`

This should be `faceMetrics.Ascent.Round()` or `faceMetrics.Ascent.Ceil()` to specified the dot position. Height means a line height, not the baseline height.

**Comment by hajimehoshi** [comment] 2020-10-27 04:00
After changing Height to Ascent, I got a better result

![image](https://user-images.githubusercontent.com/16950/97255482-12ffb700-1854-11eb-86d2-a62a63fa0b0e.png)

Looks like there is 1px differences. I'll take a look later.

**Comment by hajimehoshi** [comment] 2020-10-30 16:07
Hi, I simplified the code and this worked:

```go
func DrawTextInBox(dst *ebiten.Image, str string, face font.Face, x, y int) image.Point {
        bounds := text.BoundString(face, str)

        boundsX, boundsY := float64(bounds.Min.X + x), float64(bounds.Min.Y + y)
        boundsW, boundsH := float64(bounds.Dx()), float64(bounds.Dy())

        ebitenutil.DrawRect(dst, boundsX, boundsY, boundsW, boundsH, color.Black)
        text.Draw(dst, str, face, x, y, color.White)

        return image.Point{
                X: bounds.Dx(),
                Y: bounds.Dy(),
        }
}
```

![image](https://user-images.githubusercontent.com/16950/97728930-7bc98680-1b15-11eb-895a-e6a8711108e7.png)


The point is, use the bounds's left-upper point instead of x/y.

**Comment by hajimehoshi** [comment] 2020-12-09 17:06
Let me close this. Feel free to reopen this when you found another question.

**Closed by hajimehoshi** 2020-12-09 17:06 UTC
Labels: question
