### ISSUE TITLE
SIGSEGV "rotate" example in Alpine Linux

### ISSUE THREAD

**Issue by Enrico204** [hajimehoshi/ebiten#1688] opened 2021-06-28 17:11 UTC
I tried to run the "rotate" example after installing Ebiten (`go run -tags=example github.com/hajimehoshi/ebiten/v2/examples/rotate`), and unfortunately there is a crash:

```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x58c87c]

goroutine 21 [running]:
github.com/hajimehoshi/ebiten/v2/internal/glfw.(*Window).GetAttrib(...)
        /root/go/pkg/mod/github.com/hajimehoshi/ebiten/v2@v2.1.2/internal/glfw/glfw_notwindows.go:109
github.com/hajimehoshi/ebiten/v2/internal/uidriver/glfw.(*UserInterface).loop(0x75e000, 0x0, 0x0)
        /root/go/pkg/mod/github.com/hajimehoshi/ebiten/v2@v2.1.2/internal/uidriver/glfw/ui.go:949 +0x7c
github.com/hajimehoshi/ebiten/v2/internal/uidriver/glfw.(*UserInterface).Run.func1(0x75e000, 0xc0000863c0)
        /root/go/pkg/mod/github.com/hajimehoshi/ebiten/v2@v2.1.2/internal/uidriver/glfw/run_notsinglethread.go:52 +0xd4
created by github.com/hajimehoshi/ebiten/v2/internal/uidriver/glfw.(*UserInterface).Run
        /root/go/pkg/mod/github.com/hajimehoshi/ebiten/v2@v2.1.2/internal/uidriver/glfw/run_notsinglethread.go:36 +0x185
exit status 2
```

I suppose that the `w.w` variable is `nil` here, as far as I understand by the stacktrace: https://github.com/hajimehoshi/ebiten/blob/8ab047853ef7ca7deaa9ef02570e9752c148badd/internal/glfw/glfw_notwindows.go#L109

My environment is the following:
* Alpine Linux 3.14 x86_64
* `dwm` as (tiled) window manager
* Go 1.16.5
* Ebiten v2.1.2
* I installed all dependencies listed in the installation page

The same code runs OK in Debian 10 (latest stable) using `dwm` and the same Go version. So apparently there is something about Alpine.

Let me know if you need any test :-)

**Comment by hajimehoshi** [comment] 2021-06-28 17:20
Thanks, I'll take a look!

**Comment by hajimehoshi** [comment] 2021-06-28 17:25
Apparently there was a hidden error and this error was not shown correctly. Could you try Ebiten `6c4edf8605ea83a8c582cd228f230d1dbda213ce` ?

```
go get github.com/hajimehoshi/ebiten/v2@6c4edf8605ea83a8c582cd228f230d1dbda213ce 
```

**Comment by Enrico204** [comment] 2021-06-29 08:47
Unfortunately the commit is not fixing completely this issue. I dug a bit in the code and I discovered that the issue is because `loop()` is called after `init()` regardless of the error. I created a merge request with the rest of the bug fix :-)

I tested the fix (I mean, your commit + the merge request) and it's working (i.e. it exits with the error: `GLX: Failed to create context: GLXBadFBConfig` instead of crashing)

**Comment by Enrico204** [comment] 2021-06-29 09:06
(apparently the GLXBadFBConfig error is because my old netbook supports only OpenGL up to 1.4, and `ebiten` is using 2.1 as minimum - so I think that I'll use the software renderer to test in mobility :-D)

**Comment by hajimehoshi** [comment] 2021-06-29 09:49
Ah, thank you for fixing this! I have reviewed your PR

**Comment by hajimehoshi** [comment] 2021-06-29 14:51
Thank you for fixing this!

As you have already confirmed the root cause, I'll close this.

**Closed by hajimehoshi** 2021-06-29 14:51 UTC
Labels: bug, os:linux
