### ISSUE TITLE
fork gomobile and use it to avoid the dependency conflictions

### ISSUE THREAD

**Issue by tinne26** [hajimehoshi/ebiten#2803] opened 2023-10-07 15:55 UTC
### Ebitengine Version

`>=v2.6.0`

### Go Version (`go version`)

go1.21.1

### What steps will reproduce the problem?

Initialize a module, e.g.:
`go mod init shinydep`

Create a trivial `main.go` file using any third-party package depending on Ebitengine <v2.6.0:
```Golang
package main

import "github.com/hajimehoshi/ebiten/v2"
import "github.com/tinne26/etxt"
import "github.com/quasilyte/ebitengine-input"

var lib    = etxt.NewFontLibrary()
var action = input.Action(1)
var blend  = ebiten.Blend{}

func main() {}
```
*(Showing both etxt and ebitengine-input because the two are affected, but any one of them in isolation is enough to reproduce)*

Run `go mod tidy` to add module requirements and sums.

### What is the expected result?

Successful `go mod tidy` execution.

### What happens instead?

```
go: finding module for package github.com/tinne26/etxt
go: finding module for package github.com/hajimehoshi/ebiten/v2
go: finding module for package github.com/quasilyte/ebitengine-input
go: found github.com/hajimehoshi/ebiten/v2 in github.com/hajimehoshi/ebiten/v2 v2.6.1
go: found github.com/quasilyte/ebitengine-input in github.com/quasilyte/ebitengine-input v0.9.0
go: found github.com/tinne26/etxt in github.com/tinne26/etxt v0.0.8
go: shinydep imports
        github.com/hajimehoshi/ebiten/v2 imports
        github.com/hajimehoshi/ebiten/v2/internal/ui imports
        golang.org/x/mobile/app imports
        golang.org/x/exp/shiny/driver/gldriver: ambiguous import: found package golang.org/x/exp/shiny/driver/gldriver in multiple modules:
        golang.org/x/exp v0.0.0-20190731235908-ec7cb31e5a56 (C:\Users\username\go\pkg\mod\golang.org\x\exp@v0.0.0-20190731235908-ec7cb31e5a56\shiny\driver\gldriver)
        golang.org/x/exp/shiny v0.0.0-20230817173708-d852ddb80c63 (C:\Users\username\go\pkg\mod\golang.org\x\exp\shiny@v0.0.0-20230817173708-d852ddb80c63\driver\gldriver)
go: shinydep imports
        github.com/hajimehoshi/ebiten/v2 imports
        github.com/hajimehoshi/ebiten/v2/internal/ui imports
        golang.org/x/mobile/app imports
        golang.org/x/exp/shiny/screen: ambiguous import: found package golang.org/x/exp/shiny/screen in multiple modules:
        golang.org/x/exp v0.0.0-20190731235908-ec7cb31e5a56 (C:\Users\username\go\pkg\mod\golang.org\x\exp@v0.0.0-20190731235908-ec7cb31e5a56\shiny\screen)       
        golang.org/x/exp/shiny v0.0.0-20230817173708-d852ddb80c63 (C:\Users\username\go\pkg\mod\golang.org\x\exp\shiny@v0.0.0-20230817173708-d852ddb80c63\screen)
```

### Anything else you feel useful to add?

This was already seen on <https://github.com/hajimehoshi/ebiten/issues/2769>, but I think the impact was underestimated; it affects many major libraries in the ecosystem.

Users are forced to run `go get github.com/hajimehoshi/ebiten/v2` manually first in order to avoid the problem, as running `go mod tidy` directly will fail.

I don't know if this is considered a compatibility break or not, and I don't know if there's anything else that can be done (as I understand `shiny` is not stable and so there can be problems adapting to its changes), but this does have a non-trivial impact on third-party package users used to the `go mod tidy` workflow and basically forces third-party package developers to either raise the Ebitengine version to v2.6.0 for their packages or write additional notes on how to bypass the problem. And of course, beyond [quasilyte/ebitengine-input](https://github.com/quasilyte/ebitengine-input) and [tinne26/etxt](https://github.com/tinne26/etxt), this should also affect [yohamta/donburi](https://github.com/yohamta/donburi), [ebitenui](https://github.com/ebitenui/ebitenui), [SolarLune/resound](https://github.com/SolarLune/resound) and almost every package on [sedyh/awesome-ebitengine](https://github.com/sedyh/awesome-ebitengine) that depends on Ebitengine.

To clarify, I mostly created this issue because I wanted to visibilize and document the problem and workarounds for affected users and package maintainers.

CC @SolarLune @quasilyte @yohamta @mcarpenter622

**Comment by hajimehoshi** [comment] 2023-10-07 16:06
Yes. This already happens in v2.5.9. This is due to a problematic nested modules. Please remove the dependency on `golang.org/x/exp`.

```sh
go get golang.org/x/exp@none
go mod tidy
```

**Comment by hajimehoshi** [comment] 2023-10-07 16:12
I marked this as `wontfix` as there is nothing we can do other than the above hack.

**Comment by hajimehoshi** [comment] 2023-10-07 16:16
I tried the reproducible case @tinne26 reported and actually this cannot resolve the dependency.

I'll try to vendor gomobile, modify it to remove the dependency on shiny.

**Comment by tinne26** [comment] 2023-10-07 16:25
Oh, I didn't know that `go get @none` existed, interesting.

**Comment by hajimehoshi** [comment] 2023-10-07 16:26
Unfortunately vendoring gomobile didn't fix this issue.

The solution would not be trivial. Probably I'll fork gomobile for ours. I'll reset the milestone.

**Comment by hajimehoshi** [comment] 2023-10-07 16:30
Hmm, forking gomobile would cause another issue: `golang.org/x/mobile/app` to invoke JVM functions outside of Ebitengine would no longer be available. 🤔

**Comment by hajimehoshi** [comment] 2023-10-07 17:38
If we can admit such slight breaking changes, we can fork gomobile and use it in v2.7. Let's investigate it.

**Comment by divVerent** [comment] 2024-01-29 15:25
x/mobile/app missing is "slight breaking changes"?

Well, I assume it's a slight breaking change if its functionality is provided by another way... in my case that's just two things: RunOnJVM, and I once have a _ dependency on it to ensure its own init() runs before mine so I can override logging on iOS.

**Comment by hajimehoshi** [comment] 2024-01-29 16:40
Note to myself: When cloning gomobile, let's try to fix the go.mod generation by `go list -m all` at https://github.com/golang/mobile/blob/master/cmd/gomobile/bind.go#L236

**Comment by hajimehoshi** [comment] 2024-01-29 16:42
> x/mobile/app missing is "slight breaking changes"?

I think so. The main usage should be RunOnJVM.

> Well, I assume it's a slight breaking change if its functionality is provided by another way... in my case that's just two things: RunOnJVM, and I once have a _ dependency on it to ensure its own init() runs before mine so I can override logging on iOS.

What is the overwriding the logging for iOS?

**Comment by divVerent** [comment] 2024-01-29 17:00
https://github.com/divVerent/aaaaxy/blob/main/internal/log/log_ios.go

This is necessary to get any logging at all, as otherwise all log messages are considered "private" and thus logging is exclusively available in the Simulator.

The execution order of init() is necessary to run after this: https://cs.opensource.google/go/x/mobile/+/master:internal/mobileinit/mobileinit_ios.go;l=34;drc=80cb72e7af8e71b65e7d9e59fb4ec5d620134608

**Comment by hajimehoshi** [comment] 2024-01-29 18:37
> The execution order of init() is necessary 

OK, the order matters. However, I feel like this is out of scope of compatibility guarantee in general.

**Comment by divVerent** [comment] 2024-01-29 19:27
Yeah, the main thing we'd need is RunOnJVM. If golang.org/x/mobile is no longer used, we'll also no longer get its logging routine and I'll be happy.

**Comment by hajimehoshi** [comment] 2024-02-25 07:30
This is integrated into #2899

**Closed by hajimehoshi** 2024-02-25 07:30 UTC
Labels: bug, os:android, os:ios, needs-investigation
