### ISSUE TITLE
NewImageFromImage problems: erasing source image, crashing when calling GL functions if source image variable is set to nil after NewImageFromImage call

### ISSUE THREAD

**Issue by AmanitaVerna** [hajimehoshi/ebiten#1670] opened 2021-06-12 22:08 UTC
NewImageFromImage seems to have some issues.

This test code, run inside either a Game's Update or its Draw method, crashes reliably:
```go
testPngFile, err = os.Open("testdata/testPNG2.png")
r := bufio.NewReader(testPngFile)
var pngImg image.Image
pngImg, err = png.Decode(r)
eImg := ebiten.NewImageFromImage(pngImg)
pngImg = nil
time.Sleep(time.Second)
eImg.At(0, 0)
```

The test image is a 32-bit 1x1 pixel PNG whose single pixel is RGBA FF FF FF FF, but this also happens with larger images and seems to happen with 24-bit PNGs as well. I created both the 32-bit and 24-bit 1x1 test PNGs with Paint.NET, but it was happening with images from other sources as well.

One of the crashes:
```
Exception 0xc0000005 0x0 0x6c8 0x7ffa13657630
PC=0x7ffa13657630

syscall.Syscall(0x7ffa13657600, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0)
	C:/Program Files/Go/src/runtime/syscall_windows.go:330 +0xe9
github.com/hajimehoshi/ebiten/v2/internal/graphicsdriver/opengl/gl.Flush(...)
	C:/Users/Amani/Documents/Go/pkg/mod/github.com/hajimehoshi/ebiten/v2@v2.1.1/internal/graphicsdriver/opengl/gl/package_windows.go:184
[etc]
```

It looks like the pointer to the image it's passing no longer points to anything valid.

It isn't always the same GL function, and if there's no Sleep call, it *sometimes* crashes and sometimes doesn't, and all of this makes me suspect the garbage collector is involved. I actually added the Sleep call to the test code above so that it would crash every time instead of only sometimes. Also, when it didn't crash, At(0,0) sometimes returned RGBA 0 0 0 0 instead of the pixel's actual RGBA value, which is FF FF FF FF.

Also, if I don't set pngImage to nil, it doesn't crash, but the pngImg's pixel data appears to have been erased, replaced with all RGBA 0 0 0 0 pixels, which doesn't seem like something that should be happening.

Doing this instead of calling NewImageFromImage avoids all of these problems, so I figure something must be going very wrong with whatever NewImageFromImage is doing:
```go
w, h := pngImg.Bounds().Dx(), pngImg.Bounds().Dy()
eImg := ebiten.NewImage(w, h)
for y := 0; y < h; y++ {
	for x := 0; x < w; x++ {
		eImg.Set(x, y, pngImg.At(x, y))
	}
}
```

Ebiten version: 2.1.1
OS: Windows 10 Pro, version 20H2

If you have any questions, I'd be happy to answer them.

**Comment by hajimehoshi** [comment] 2021-06-13 04:32
Hi, which version of Ebiten are you using?

I couldn't reproduce this issue with this code:

```
func TestNewImageFromImageAndSetSourceNil(t *testing.T)  {
        img0 := image.NewRGBA(image.Rect(0, 0, 1, 1))
        img1 := NewImageFromImage(img0)
        img0 = nil
        runtime.GC()
        img1.At(0, 0)
}
```

**Comment by AmanitaVerna** [comment] 2021-06-13 04:38
2.1.1 (ah, you noticed, okay) and I've been running it through something like this (because I was having problems running the test code before RunGame, if I remember correctly):
```go
type ATest struct {
}

func (a *ATest) Update() (err error) {
	//this is where the code would be
	err = errors.New("done")
	return
}
func (a *ATest) Draw(screen *ebiten.Image) {
}
func (a *ATest) Layout(ow, oh int) (int, int) {
	return 1920, 1080
}
func Test_A(t *testing.T) {
	ebiten.SetWindowSize(640, 480)
	ebiten.SetWindowTitle("Test")
	ebiten.RunGame(&ATest{})
}
```

**Comment by AmanitaVerna** [comment] 2021-06-13 04:43
I just tried your first test function (outside the ebiten namespace, so I changed the third line to `img1 := ebiten.NewImageFromImage(img0)`) and I got this (which is why I was doing the convoluted thing in my last post):
```--- FAIL: TestNewImageFromImageAndSetSourceNil (0.00s)
panic: buffered: the command queue is not available yet at Pixels [recovered]
	panic: buffered: the command queue is not available yet at Pixels
goroutine 6 [running]:
testing.tRunner.func1.2(0x2e7040, 0xc00004c000)
	C:/Program Files/Go/src/testing/testing.go:1143 +0x345
testing.tRunner.func1(0xc000043200)
	C:/Program Files/Go/src/testing/testing.go:1146 +0x4b6
panic(0x2e7040, 0xc00004c000)
	C:/Program Files/Go/src/runtime/panic.go:965 +0x1c7
github.com/hajimehoshi/ebiten/v2/internal/buffered.checkDelayedCommandsFlushed(...)
	C:/Users/Amani/Documents/Go/pkg/mod/github.com/hajimehoshi/ebiten/v2@v2.1.1/internal/buffered/command.go:90
github.com/hajimehoshi/ebiten/v2/internal/buffered.(*Image).Pixels(0xc000058b80, 0x0, 0x0, 0x1, 0x1, 0x7d46b, 0x39d358, 0x0, 0xc000000001, 0x100000000)
	C:/Users/Amani/Documents/Go/pkg/mod/github.com/hajimehoshi/ebiten/v2@v2.1.1/internal/buffered/image.go:130 +0x417
github.com/hajimehoshi/ebiten/v2/internal/mipmap.(*Mipmap).Pixels(...)
	C:/Users/Amani/Documents/Go/pkg/mod/github.com/hajimehoshi/ebiten/v2@v2.1.1/internal/mipmap/mipmap.go:85
github.com/hajimehoshi/ebiten/v2.(*Image).At(0xc000058bc0, 0x0, 0x0, 0x1, 0xc000058b40)
	C:/Users/Amani/Documents/Go/pkg/mod/github.com/hajimehoshi/ebiten/v2@v2.1.1/image.go:665 +0xda
github.com/amanitaverna/frost/gui.TestNewImageFromImageAndSetSourceNil(0xc000043200)
	c:/Users/Amani/Documents/Go/src/github.com/amanitaverna/frost/gui/imageCache_test.go:30 +0x85
testing.tRunner(0xc000043200, 0x39cd20)
	C:/Program Files/Go/src/testing/testing.go:1193 +0xef
created by testing.(*T).Run
	C:/Program Files/Go/src/testing/testing.go:1238 +0x2b3
FAIL	github.com/amanitaverna/frost/gui	0.288s
FAIL```

**Comment by hajimehoshi** [comment] 2021-06-13 04:47
> because I was having problems running the test code before RunGame, if I remember correctly

Yeah, and actually Ebiten tests in `image_test.go` runs after RunGame (see `internal/testing.MainWithRunLoop`).

**Comment by hajimehoshi** [comment] 2021-06-13 04:47
> I just tried your first test function (outside the ebiten namespace, so I changed the third line to img1 := ebiten.NewImageFromImage(img0)) and I got this (which is why I was doing the convoluted thing in my last post):

Did you run this in Update?

**Comment by hajimehoshi** [comment] 2021-06-13 04:52
Another question: Which version of Go are you using?

**Comment by AmanitaVerna** [comment] 2021-06-13 04:54
I'm using Go 1.16.5.

And yes, interestingly, it seemed to work fine when I ran it in Update when I ran the individual test (through vs code), but when I ran `go test` from powershell instead, I got a shader compilation error (what the heck???). And when I replaced the `runtime.GC()` line with `time.Sleep(time.Second)`, and ran just the individual test, I got this:

```
Exception 0xc0000005 0x0 0xed8 0x7ff9bbf5b6a9
PC=0x7ff9bbf5b6a9

syscall.Syscall6(0x7ff9bbf5b6a0, 0x4, 0x8892, 0x0, 0x80, 0xc0000d4280, 0x0, 0x0, 0x0, 0x0, ...)
	C:/Program Files/Go/src/runtime/syscall_windows.go:343 +0xf2
github.com/hajimehoshi/ebiten/v2/internal/graphicsdriver/opengl/gl.BufferSubData(...)
	C:/Users/Amani/Documents/Go/pkg/mod/github.com/hajimehoshi/ebiten/v2@v2.1.1/internal/graphicsdriver/opengl/gl/package_windows.go:125
github.com/hajimehoshi/ebiten/v2/internal/graphicsdriver/opengl.(*context).arrayBufferSubData(0x8e5388, 0xc0000d4280, 0x20, 0x20)
	C:/Users/Amani/Documents/Go/pkg/mod/github.com/hajimehoshi/ebiten/v2@v2.1.1/internal/graphicsdriver/opengl/context_desktop.go:414 +0xc5
github.com/hajimehoshi/ebiten/v2/internal/graphicsdriver/opengl.(*Graphics).SetVertices(0x8e5360, 0xc0000d4280, 0x20, 0x20, 0xc0002486d0, 0x6, 0x8)
	C:/Users/Amani/Documents/Go/pkg/mod/github.com/hajimehoshi/ebiten/v2@v2.1.1/internal/graphicsdriver/opengl/graphics.go:147 +0x5b
github.com/hajimehoshi/ebiten/v2/internal/graphicscommand.(*commandQueue).flush(0x8e52c0, 0x4a0d01, 0xc000240101)
	C:/Users/Amani/Documents/Go/pkg/mod/github.com/hajimehoshi/ebiten/v2@v2.1.1/internal/graphicscommand/command.go:276 +0x6c2
github.com/hajimehoshi/ebiten/v2/internal/graphicscommand.(*commandQueue).Flush.func1(0xc000086540, 0xc000051e58)
	C:/Users/Amani/Documents/Go/pkg/mod/github.com/hajimehoshi/ebiten/v2@v2.1.1/internal/graphicscommand/command.go:206 +0x31
github.com/hajimehoshi/ebiten/v2/internal/thread.(*OSThread).Loop(0xc000089270)
	C:/Users/Amani/Documents/Go/pkg/mod/github.com/hajimehoshi/ebiten/v2@v2.1.1/internal/thread/thread.go:51 +0xa3
github.com/hajimehoshi/ebiten/v2/internal/uidriver/glfw.(*UserInterface).Run(0x8df220, 0x62da88, 0x8e51e0, 0x4, 0x438)
	C:/Users/Amani/Documents/Go/pkg/mod/github.com/hajimehoshi/ebiten/v2@v2.1.1/internal/uidriver/glfw/run_notsinglethread.go:58 +0x1ac
github.com/hajimehoshi/ebiten/v2.RunGame(0x62d100, 0x92b808, 0x0, 0x0)
	C:/Users/Amani/Documents/Go/pkg/mod/github.com/hajimehoshi/ebiten/v2@v2.1.1/run.go:172 +0xed
github.com/amanitaverna/frost/gui.Test_A(0xc000084600)
	c:/Users/Amani/Documents/Go/src/github.com/amanitaverna/frost/gui/imageCache_test.go:56 +0x6f
testing.tRunner(0xc000084600, 0x5e35f0)
	C:/Program Files/Go/src/testing/testing.go:1193 +0xef
created by testing.(*T).Run
	C:/Program Files/Go/src/testing/testing.go:1238 +0x2b3

goroutine 1 [chan receive, locked to thread]:
testing.(*T).Run(0xc000084600, 0x58c10a, 0x6, 0x5e35f0, 0x316901)
	C:/Program Files/Go/src/testing/testing.go:1239 +0x2da
testing.runTests.func1(0xc000084480)
	C:/Program Files/Go/src/testing/testing.go:1511 +0x7f
testing.tRunner(0xc000084480, 0xc0000cbde0)
	C:/Program Files/Go/src/testing/testing.go:1193 +0xef
testing.runTests(0xc00009c360, 0x8c53c0, 0x3, 0x3, 0xc029817b06a70638, 0x7077db231, 0x8e5240, 0x592735)
	C:/Program Files/Go/src/testing/testing.go:1509 +0x310
testing.(*M).Run(0xc0000d8200, 0x0)
	C:/Program Files/Go/src/testing/testing.go:1417 +0x1f5
main.main()
	_testmain.go:47 +0x145

goroutine 20 [chan receive]:
github.com/hajimehoshi/ebiten/v2/internal/thread.(*OSThread).Call(0xc000089270, 0xc000089dc0, 0x30001, 0xc000089dc0)
	C:/Users/Amani/Documents/Go/pkg/mod/github.com/hajimehoshi/ebiten/v2@v2.1.1/internal/thread/thread.go:69 +0x6d
github.com/hajimehoshi/ebiten/v2/internal/graphicscommand.runOnMainThread(0xc000089dc0, 0xc000089dc0, 0x92b380)
	C:/Users/Amani/Documents/Go/pkg/mod/github.com/hajimehoshi/ebiten/v2@v2.1.1/internal/graphicscommand/thread.go:35 +0x4b
github.com/hajimehoshi/ebiten/v2/internal/graphicscommand.(*commandQueue).Flush(0x8e52c0, 0x100000000000000, 0x1fbfc4b0158)
	C:/Users/Amani/Documents/Go/pkg/mod/github.com/hajimehoshi/ebiten/v2@v2.1.1/internal/graphicscommand/command.go:205 +0x5e
github.com/hajimehoshi/ebiten/v2/internal/graphicscommand.FlushCommands(...)
	C:/Users/Amani/Documents/Go/pkg/mod/github.com/hajimehoshi/ebiten/v2@v2.1.1/internal/graphicscommand/command.go:304
github.com/hajimehoshi/ebiten/v2/internal/restorable.(*Image).readPixelsFromGPUIfNeeded(0xc0000d6d80, 0x10, 0xc000248730)
	C:/Users/Amani/Documents/Go/pkg/mod/github.com/hajimehoshi/ebiten/v2@v2.1.1/internal/restorable/image.go:428 +0x45
github.com/hajimehoshi/ebiten/v2/internal/restorable.(*Image).At(0xc0000d6d80, 0x1, 0x6, 0x526c80, 0x1, 0xc000248730)
	C:/Users/Amani/Documents/Go/pkg/mod/github.com/hajimehoshi/ebiten/v2@v2.1.1/internal/restorable/image.go:446 +0x7f
github.com/hajimehoshi/ebiten/v2/internal/atlas.(*Image).at(0xc0000d7180, 0x1, 0x1, 0xc000248730, 0x2030000, 0x20)
	C:/Users/Amani/Documents/Go/pkg/mod/github.com/hajimehoshi/ebiten/v2@v2.1.1/internal/atlas/image.go:533 +0xbc
github.com/hajimehoshi/ebiten/v2/internal/atlas.(*Image).Pixels(0xc0000d7180, 0x0, 0x0, 0x1, 0x1, 0x0, 0x0, 0x0, 0x0, 0x0)
	C:/Users/Amani/Documents/Go/pkg/mod/github.com/hajimehoshi/ebiten/v2@v2.1.1/internal/atlas/image.go:509 +0x18b
github.com/hajimehoshi/ebiten/v2/internal/buffered.(*Image).Pixels(0xc0000d7140, 0x0, 0x0, 0x1, 0x1, 0x5e3e08, 0xc00013e5f0, 0xc0000d1313, 0x1, 0xc00013e5f0)
	C:/Users/Amani/Documents/Go/pkg/mod/github.com/hajimehoshi/ebiten/v2@v2.1.1/internal/buffered/image.go:139 +0x27a
github.com/hajimehoshi/ebiten/v2/internal/mipmap.(*Mipmap).Pixels(...)
	C:/Users/Amani/Documents/Go/pkg/mod/github.com/hajimehoshi/ebiten/v2@v2.1.1/internal/mipmap/mipmap.go:85
github.com/hajimehoshi/ebiten/v2.(*Image).At(0xc0000d71c0, 0x0, 0x0, 0x1, 0xc0000d7100)
	C:/Users/Amani/Documents/Go/pkg/mod/github.com/hajimehoshi/ebiten/v2@v2.1.1/image.go:665 +0xda
github.com/amanitaverna/frost/gui.(*ATest).Update(0x92b808, 0xc000179800, 0x0)
	c:/Users/Amani/Documents/Go/src/github.com/amanitaverna/frost/gui/imageCache_test.go:44 +0x92
github.com/hajimehoshi/ebiten/v2.(*imageDumper).update(0xc00013e5a0, 0xc00013e5a0, 0x5e3f80)
	C:/Users/Amani/Documents/Go/pkg/mod/github.com/hajimehoshi/ebiten/v2@v2.1.1/imagedumper_desktop.go:112 +0x6b
github.com/hajimehoshi/ebiten/v2.(*imageDumperGame).Update(0xc000178c00, 0x0, 0xc00014f470)
	C:/Users/Amani/Documents/Go/pkg/mod/github.com/hajimehoshi/ebiten/v2@v2.1.1/run.go:115 +0x52
github.com/hajimehoshi/ebiten/v2.(*uiContext).update(0x8e51e0, 0x1, 0x0, 0x0)
	C:/Users/Amani/Documents/Go/pkg/mod/github.com/hajimehoshi/ebiten/v2@v2.1.1/uicontext.go:197 +0xd2
github.com/hajimehoshi/ebiten/v2.(*uiContext).Update(0x8e51e0, 0x4084000000000000, 0x407e000000000000)
	C:/Users/Amani/Documents/Go/pkg/mod/github.com/hajimehoshi/ebiten/v2@v2.1.1/uicontext.go:153 +0xd3
github.com/hajimehoshi/ebiten/v2/internal/uidriver/glfw.(*UserInterface).loop(0x8df220, 0x0, 0x0)
	C:/Users/Amani/Documents/Go/pkg/mod/github.com/hajimehoshi/ebiten/v2@v2.1.1/internal/uidriver/glfw/ui.go:964 +0x15f
github.com/hajimehoshi/ebiten/v2/internal/uidriver/glfw.(*UserInterface).Run.func1(0x8df220, 0xc0000e66c0)
	C:/Users/Amani/Documents/Go/pkg/mod/github.com/hajimehoshi/ebiten/v2@v2.1.1/internal/uidriver/glfw/run_notsinglethread.go:52 +0xe5
created by github.com/hajimehoshi/ebiten/v2/internal/uidriver/glfw.(*UserInterface).Run
	C:/Users/Amani/Documents/Go/pkg/mod/github.com/hajimehoshi/ebiten/v2@v2.1.1/internal/uidriver/glfw/run_notsinglethread.go:36 +0x186
rax     0x0
rbx     0xc0000092e0
rcx     0x8892
rdi     0x43e05a3000
rsi     0xc000051c18
rbp     0xc000051bb8
rsp     0x43e11ffa68
r8      0x80
r9      0xc0000d4280
r10     0x1
r11     0xc00009cb88
r12     0x52efa0
r13     0x5e3580
r14     0x7c
r15     0xffffffffffffffff
rip     0x7ff9bbf5b6a9
rflags  0x10246
cs      0x33
fs      0x53
gs      0x2b
FAIL	github.com/amanitaverna/frost/gui	1.519s
FAIL
```

The code that resulted in that:
```go
type ATest struct {
}

func (a *ATest) Update() (err error) {
	img0 := image.NewRGBA(image.Rect(0, 0, 1, 1))
	img1 := ebiten.NewImageFromImage(img0)
	img0 = nil
	time.Sleep(time.Second)
	img1.At(0, 0)
	err = errors.New("done")
	return
}
func (a *ATest) Draw(screen *ebiten.Image) {
}
func (a *ATest) Layout(ow, oh int) (int, int) {
	return 1920, 1080
}
func Test_A(t *testing.T) {
	//ebiten.SetWindowSize(640, 480)
	ebiten.SetWindowTitle("Test")
	ebiten.RunGame(&ATest{})
}
```

**Comment by AmanitaVerna** [comment] 2021-06-13 05:00
I just checked to see if the code in my last post does the same thing with the current git version (by updating my go.mod with `go get github.com/hajimehoshi/ebiten/v2@741548351c993adf72ccb235a6a0acdbc19c3fd2`), and I got the same exception in BufferSubData when I ran go test.

**Comment by hajimehoshi** [comment] 2021-06-13 05:03
I still cannot reproduce the issue on Windows by executing the test you posted. Hmm, this sounds like an issue in the OpenGL driver, but I'm not sure. I'll take a look further.

**Comment by AmanitaVerna** [comment] 2021-06-13 05:10
If it helps at all to know this, I have an NVidia GTX 750 Ti, and currently have NVidia's 466.11 drivers installed.

**Comment by hajimehoshi** [comment] 2021-06-13 05:20
Interesting. I found a suspicious crash with macOS with the test...

```
$ go test ./examples/test/                                                                                                                                                                                                                                                            
2021-06-13 14:19:46.583 test.test[71258:27242575] *** Terminating app due to uncaught exception 'NSInternalInconsistencyException', reason: 'NSWindow drag regions should only be invalidated on the Main Thread!'                                                                    
*** First throw call stack:                                                                                                                                                                                                                                                           
(                                                                                                                                                                                                                                                                                     
        0   CoreFoundation                      0x00007fff207b998b __exceptionPreprocess + 242                                                                                                                                                                                        
        1   libobjc.A.dylib                     0x00007fff204f1d92 objc_exception_throw + 48                                                                                                                                                                                          
        2   CoreFoundation                      0x00007fff207e2086 -[NSException raise] + 9                                                                                                                                                                                           
        3   AppKit                              0x00007fff22f64872 -[NSWindow(NSWindow_Theme) _postWindowNeedsToResetDragMarginsUnlessPostingDisabled] + 321                                                                                                                          
        4   AppKit                              0x00007fff22f4f44a -[NSWindow _initContent:styleMask:backing:defer:contentView:] + 1296                                                                                                                                               
        5   AppKit                              0x00007fff22f4ef33 -[NSWindow initWithContentRect:styleMask:backing:defer:] + 42                                                                                                                                                      
        6   test.test                           0x00000000041b7aeb _glfwPlatformCreateWindow + 491                                                                                                                                                                                    
        7   test.test                           0x00000000041b07f5 glfwCreateWindow + 485                                                                                                                                                                                             
        8   test.test                           0x00000000041bd9fb _cgo_d63f5f7b2d6a_Cfunc_glfwCreateWindow + 43                                                                                                                                                                      
        9   test.test                           0x00000000040720d0 runtime.asmcgocall + 112                                                                                                                                                                                           
)                                                                                                                                                                                                                                                                                     
libc++abi: terminating with uncaught exception of type NSException                                                                                                                                                                                                                    
SIGABRT: abort                                                                                                                                                                                                                                                                        
PC=0x7fff20617946 m=3 sigcode=0                    
```

**Comment by hajimehoshi** [comment] 2021-06-13 05:29
> And yes, interestingly, it seemed to work fine when I ran it in Update when I ran the individual test (through vs code), but when I ran go test from powershell instead, I got a shader compilation error (what the heck???). 

The cause is that RunGame must be executed on a main thread while your test doesn't. You would need to some hack to run the test on the main thread (e.g., testing.Main).

Then, the problems still exists with a regular execution (not tests), right?

**Comment by AmanitaVerna** [comment] 2021-06-13 20:22
Ah, thanks! I didn't realize that would be an issue. I just (finally) got it working by writing a hack using TestMain, init(), runtime.LockOSThread(), and some stuff with channels, to get RunGame and the tests to all run on the main thread.

RunGame and NewImageFromImage in Update both seem to be working fine when run as a normal program, not in tests, presumably because RunGame is being called from main already there. I think the problem must have just been with the tests not being run on the main thread, like you said. I was trying to test my code before I wrote anything that used it, so I hadn't tried it in a regular program yet, and not trying the failing code in a regular program before posting this issue was perhaps an oversight on my part. 

I really appreciate your help with figuring out what the issue was, even though it turned out not to be anything wrong with ebiten! (I do wonder if there's any way for ebiten to determine if RunGame is being called from the main thread, and if not, to either warn about it, or to try to force it to be run on the main thread?)

**Comment by hajimehoshi** [comment] 2021-06-14 03:33
Thank you for confirming!

> I do wonder if there's any way for ebiten to determine if RunGame is being called from the main thread, and if not, to either warn about it, or to try to force it to be run on the main thread?

Yeah I thought that too, but apparently it is almost impossible to detect whether the current thread is the main or not with Go.

As the issue was solved, let me close this.

**Closed by hajimehoshi** 2021-06-14 03:33 UTC
Labels: bug, os:windows

**Comment by MrWormHole** [comment] 2021-12-27 16:24
I have come across this bug "panic: buffered: the command queue is not available yet at Pixels" 

The root cause was doing ebiten.NewImageFromImage with image that was *ebiten.Image

**Comment by hajimehoshi** [comment] 2021-12-27 16:31
Yes, this is a known issue and there is no way to fix this so far.

**Comment by hajimehoshi** [comment] 2021-12-27 16:59
I came up a solution: if a given image is a `*ebiten.Image`, `NewImageFromImage` can use `DrawImage` instead of `At`.

**Comment by MrWormHole** [comment] 2021-12-27 19:15
Yea I think so, could there be a definitive error message added if NewImageFromImage gets ebiten.Image in error message like saying don't pass ebiten.Image here or this is for only image.Image?
